import assert from "node:assert/strict";
import { access, readFile, stat } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("https://ielts-ai.test/", { headers: { accept: "text/html", host: "ielts-ai.test" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the IELTS AI product shell and metadata", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<title>IELTS Pass/);
  assert.match(html, /场景化雅思学习/);
  assert.match(html, /IELTS PASS/);
  assert.match(html, /设置你的头像、名字与目标/);
  assert.match(html, /无需注册或登录/);
  assert.doesNotMatch(html, /codex-preview|SkeletonPreview|Your site is taking shape|react-loading-skeleton/i);
});

test("ships an installable cross-platform web app", async () => {
  const [manifestText, support, serviceWorker] = await Promise.all([
    readFile(new URL("../public/manifest.webmanifest", import.meta.url), "utf8"),
    readFile(new URL("../app/PwaSupport.tsx", import.meta.url), "utf8"),
    readFile(new URL("../public/sw.js", import.meta.url), "utf8"),
  ]);
  const manifest = JSON.parse(manifestText);
  assert.equal(manifest.display, "standalone");
  assert.equal(manifest.id, "./");
  assert.equal(manifest.start_url, "./?source=pwa");
  assert.equal(manifest.scope, "./");
  assert.equal(manifest.prefer_related_applications, false);
  assert.deepEqual(manifest.icons.map((icon) => icon.src), ["./icon-192.png", "./icon-512.png"]);
  assert.deepEqual(manifest.icons.map((icon) => icon.sizes), ["192x192", "512x512"]);
  assert.match(support, /beforeinstallprompt/);
  assert.match(support, /import\.meta\.env\.BASE_URL/);
  assert.match(support, /serviceWorker\.register\(`\$\{basePath\}sw\.js\?v=\$\{serviceWorkerVersion\}`/);
  assert.match(support, /安装到 Windows 或手机桌面/);
  assert.match(support, /updateViaCache: "none"/);
  assert.match(support, /controllerchange/);
  assert.match(serviceWorker, /SKIP_WAITING/);
  assert.match(serviceWorker, /cache: "no-store"/);
  assert.match(serviceWorker, /OFFLINE_DOCUMENT/);
  assert.match(serviceWorker, /self\.registration\.scope/);
  assert.match(serviceWorker, /scopedPath\("manifest\.webmanifest"\)/);
  assert.match(serviceWorker, /request\.mode === "navigate"/);
  for (const icon of ["icon-192.png", "icon-512.png"]) {
    const file = new URL(`../public/${icon}`, import.meta.url);
    await access(file);
    assert.ok((await stat(file)).size > 1_000);
  }
});

test("ships all four learning modes and persistent progress", async () => {
  const [app, data, dailyPractice, expandedVocabulary, listeningCorpus, notices, state, styles] = await Promise.all([
    readFile(new URL("../app/IeltsApp.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/learning-data.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/daily-practice-data.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/vocabulary-expanded.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/listening-corpus.ts", import.meta.url), "utf8"),
    readFile(new URL("../THIRD_PARTY_NOTICES.md", import.meta.url), "utf8"),
    readFile(new URL("../app/learning-state.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  for (const feature of ["VocabularyPractice", "ListeningPractice", "SpeakingPractice", "ReadingPractice", "ReviewView"]) {
    assert.match(app, new RegExp(feature));
  }
  assert.match(data, /label: "词汇综合训练"/);
  assert.match(app, /每日 \{vocabularyTarget\} 词/);
  const mobileNavigationBlock = app.match(/function MobileNavigation[\s\S]*?function PageHeader/)?.[0] ?? "";
  assert.equal((mobileNavigationBlock.match(/id: "/g) ?? []).length, 5);
  assert.equal((mobileNavigationBlock.match(/id: "today"/g) ?? []).length, 1);
  assert.match(mobileNavigationBlock, /<span>\{item\.icon\}<\/span><small>\{item\.label\}<\/small>/);
  assert.match(styles, /Native app shell/);
  assert.match(styles, /env\(safe-area-inset-bottom\)/);
  assert.match(styles, /\.mobile-nav button\.mobile-ai span/);
  assert.doesNotMatch(app, /先补做昨天的词汇/);
  assert.match(app, /今天已完成 \$\{completedCount\} \/ 4 项，今天下一项是/);
  assert.match(app, /localStorage\.setItem/);
  assert.match(app, /document\.visibilityState === "visible"/);
  assert.match(app, /visibilitychange/);
  assert.match(app, /pagehide/);
  assert.match(app, /unsavedSeconds >= 10/);
  assert.match(app, /页面在前台可见时累计学习时间/);
  assert.match(app, /SpeechSynthesisUtterance/);
  assert.match(app, /preferredIeltsVoiceNames/);
  assert.doesNotMatch(app, /"Flo"|"Sandy"|"Reed"/);
  assert.match(app, /createIeltsUtterance/);
  assert.match(app, /utterance\.pitch/);
  assert.match(app, /IELTS 英式标准发音/);
  assert.match(app, /IELTS 英式自然语速/);
  assert.match(app, /DailyVocabularySprint/);
  assert.match(app, /autoPronounceDailyVocabularyWord\(word\.word\)/);
  assert.match(app, /▶ 重播发音/);
  assert.match(app, /SCENE DICTATION|每天.*个听写词|听清再写准/);
  assert.match(app, /CONNECTED SPEECH|每天.*个词组|听懂自然语流/);
  assert.match(app, /Matching Headings|Matching Information|Summary Completion/);
  assert.match(app, /考官/);
  assert.match(data, /label: "口语"/);
  assert.doesNotMatch(data, /label: "口语 Part 3"/);
  assert.doesNotMatch(app, /真实考试结构/);
  assert.match(app, /Form Completion|Choose TWO|提交 10 道答案/);
  assert.match(state, /dailyVocabularyDate|dailyVocabularySeen|dailyVocabularyKnown/);
  assert.match(state, /studyPlanDays: number/);
  assert.match(state, /studyPlanStartedAt: string/);
  assert.match(state, /targetBandScore: number/);
  assert.match(state, /dailyVocabularyTarget/);
  assert.match(state, /dailyDictationTarget/);
  assert.match(state, /dailyConnectedSpeechTarget/);
  assert.match(state, /dailyReviewTarget/);
  assert.match(state, /targetScoreWorkloadFactor/);
  assert.match(state, /targetPlanFocus/);
  assert.match(state, /officialSessionsPerWeek/);
  assert.match(state, /estimatedDailyMinutes/);
  assert.match(state, /normalizeTargetBandScore/);
  assert.match(state, /targetOfficialSessionsPerWeek/);
  assert.match(state, /targetEstimatedDailyMinutes/);
  assert.match(state, /overallPlanProgress/);
  assert.match(app, /plannedOfficialSessionsForWeek/);
  assert.match(app, /weeklyOpeningTask/);
  assert.match(app, /听力、阅读、写作、口语四部分始终开放并按周轮换/);
  assert.match(app, /plannedSessions\.map/);
  assert.match(app, /openSessions\.map/);
  assert.match(app, /本周计划/);
  assert.match(app, /开放训练/);
  assert.match(app, /本周从新题开始/);
  assert.match(app, /initialTaskId/);
  assert.doesNotMatch(app, /officialTestSchedule\.slice\(0, sessionsPerWeek\)/);
  assert.match(state, /completedDailyTasks/);
  assert.match(state, /officialPracticePercent/);
  assert.match(state, /vocabularyLibraryVersion = "3600-v2-listening-corpus"/);
  assert.match(state, /isCurrentVocabularyLibrary/);
  assert.match(state, /speakingPart3Turns/);
  assert.match(state, /listeningScore/);
  assert.match(state, /localDayKey/);
  assert.match(state, /localWeekKey/);
  assert.match(state, /officialPracticeCompleted/);
  assert.match(state, /DailyStudyRecord/);
  assert.match(state, /dailyStudyHistory/);
  assert.match(state, /recordStudyActivity/);
  assert.match(state, /recordAppStudyTime/);
  assert.match(state, /activeStudySeconds/);
  assert.match(state, /activeSeconds: number/);
  assert.match(state, /StudyTimeCategory/);
  assert.match(state, /study-time:\$\{category\}/);
  assert.match(state, /existingCategorySeconds/);
  assert.match(app, /activeStudyCategory/);
  assert.match(app, /studyIdleTimeoutMs = 90_000/);
  assert.match(app, /hasPlayingStudyMedia/);
  assert.match(app, /recentlyInteracted \|\| hasPlayingStudyMedia\(\)/);
  assert.match(app, /"pointerdown", "keydown", "input", "change", "scroll", "touchstart"/);
  assert.match(app, /if \(!hydrated \|\| !activeStudyCategory\) return/);
  assert.match(state, /if \(!category\) return progress/);
  assert.match(app, /recordAppStudyTime\(progressRef\.current, seconds, localDayKey\(\), activeStudyCategory\)/);
  assert.match(app, /study-time:vocabulary/);
  assert.match(app, /study-time:listening/);
  assert.match(app, /study-time:reading/);
  assert.match(app, /study-time:speaking/);
  assert.match(app, /formatStudyDuration/);
  assert.match(state, /id: "app-active-time", label: "App 内有效学习"/);
  assert.match(state, /minutes: Math\.floor\(activeStudySeconds \/ 60\)/);
  assert.doesNotMatch(state, /minutes: 12/);
  assert.match(state, /calculateStudyStreak/);
  assert.match(state, /streak: 0/);
  assert.match(state, /streak: calculateStudyStreak\(dailyStudyHistory, today\)/);
  assert.doesNotMatch(state, /streak: 6/);
  assert.match(state, /OfficialTaskResult/);
  assert.match(state, /officialTaskResults/);
  assert.match(state, /officialTaskAttemptHistory: Record<string, OfficialTaskResult\[\]>/);
  assert.match(state, /carryoverTasks/);
  assert.match(state, /carryoverTaskDates/);
  assert.match(state, /previousStudyDate/);
  assert.match(state, /newlyMissedTasks/);
  assert.match(
    state,
    /const dailySkillOrder: Skill\[\] = \["vocabulary", "listening", "reading", "speaking"\]/,
  );
  assert.match(state, /const carryoverTasks = dailySkillOrder\.filter/);
  assert.match(state, /speakingTurnsByDate: Record<string, number>/);
  assert.match(app, /progress\.speakingTurnsByDate\[speakingProgressKey\]/);
  assert.match(app, /speakingProgressKey = `\$\{exerciseDate\}:band-\$\{difficulty\.band\}`/);
  assert.match(app, /openSkill\(nextSkill, localDayKey\(\)\)/);
  assert.match(app, /onClick=\{\(\) => onOpenSkill\(skill\.id, localDayKey\(\)\)\}/);
  assert.match(app, /onSelectSkill=\{\(skill\) => openSkill\(skill, activeContentDate\)\}/);
  assert.match(state, /dailyVocabularyCompleted/);
  assert.match(state, /dailyDictationCompleted/);
  assert.match(state, /dailyDictationSeen/);
  assert.match(state, /connectedSpeechSeen/);
  assert.match(state, /dailyVocabularyRatings/);
  assert.match(state, /dailyVocabularyAttempts/);
  assert.match(state, /reviewSchedule/);
  assert.match(state, /NotebookEntry/);
  assert.match(state, /notebook: NotebookEntry\[\]/);
  assert.match(state, /points: number/);
  assert.match(state, /pointRewards: PointReward\[\]/);
  assert.match(state, /function grantPoints/);
  assert.match(state, /progress\.pointRewards\.some\(\(item\) => item\.id === reward\.id\)/);
  assert.match(state, /kind: "audio" \| "speech"/);
  assert.match(state, /reference\?: \{/);
  assert.match(state, /reviewIntervals = \[1, 3, 7, 14, 30, 60\]/);
  assert.match(state, /scheduleWordForReview/);
  assert.match(state, /rateReviewWord/);

  const dailySource = data.match(/const dailyVocabularySource = `([\s\S]*?)`\.trim\(\)/);
  assert.ok(dailySource, "daily vocabulary source should exist");
  const words = dailySource[1].trim().split("\n").map((line) => line.split("|")[0]);
  assert.equal(words.length, 300);
  assert.equal(new Set(words).size, 300);
  assert.match(data, /getDailyVocabulary/);
  assert.match(data, /AWL 学术词族/);
  const corpusWordRows = listeningCorpus.match(/const listeningCorpusWordRows = \[([\s\S]*?)\] as const;/);
  const corpusPhraseRows = listeningCorpus.match(/const listeningCorpusPhraseRows = \[([\s\S]*?)\] as const;/);
  assert.ok(corpusWordRows, "imported listening word corpus should exist");
  assert.ok(corpusPhraseRows, "imported listening phrase corpus should exist");
  assert.equal((corpusWordRows[1].match(/^ {2}\[/gm) ?? []).length, 2684);
  assert.equal((corpusPhraseRows[1].match(/^ {2}\[/gm) ?? []).length, 1999);
  assert.match(data, /getDailyListeningVocabulary/);
  assert.match(data, /getDailyConnectedSpeechPhrases/);
  assert.match(data, /matchingHeadings|matchingInformation|trueFalseNotGiven|summary/);
  assert.match(data, /Two-way discussion|questions:/);
  assert.match(data, /formCompletion|multipleSelect|matching|multipleChoice/);
  assert.match(data, /listeningReviewEvidence/);
  assert.match(data, /为什么|怎么改进|修正信息干扰|多选题要同时核对限定词/);
  assert.match(data, /export const connectedSpeechPhrases = listeningCorpusPhrases\.map/);
  assert.match(dailyPractice, /listening-section-1-v2\.wav/);
  assert.match(dailyPractice, /natural-uk-dual-v6/);
  assert.match(await readFile(new URL("../scripts/generate-daily-listening-audio.mjs", import.meta.url), "utf8"), /spelledNameChunks/);
  assert.match(await readFile(new URL("../scripts/generate-listening-v2.py", import.meta.url), "utf8"), /spelled_name_chunks/);
  assert.match(dailyPractice, /listening-arts-centre\.wav/);
  assert.match(dailyPractice, /listening-wildlife-volunteer\.wav/);
  assert.match(dailyPractice, /自然英国女接待员 × 英国男学生/);
  assert.match(dailyPractice, /natural-uk-dual-v6/);
  assert.match(dailyPractice, /dailyRotationIndex/);
  assert.match(dailyPractice, /getDailyListeningExercise/);
  assert.match(dailyPractice, /getDailyReadingExercise/);
  assert.match(dailyPractice, /getDailySpeakingScenario/);
  assert.match(dailyPractice, /audioCues/);
  assert.match(app, /type IeltsVoiceRole = "examiner" \| "female" \| "male"/);
  assert.match(app, /listening-scrubber/);
  assert.match(app, /拖动笔记听力音频进度/);
  assert.match(app, /seekNotebookAudio/);
  assert.match(app, /currentTime = nextTime/);
  assert.match(app, /听不懂？显示字幕/);
  assert.match(app, /开始口语模拟/);
  assert.match(app, /practiceRecognition/);
  assert.match(app, /提交回答/);
  assert.match(app, /没有获得麦克风权限/);
  assert.match(app, /!draft\.trim\(\) \|\| micState === "listening"/);
  assert.match(app, /记错了/);
  assert.match(app, /重听当前问题/);
  assert.match(app, /继续播放/);
  assert.match(app, /speechSynthesis\.pause/);
  assert.match(app, /speechSynthesis\.resume/);
  assert.match(app, /字幕已隐藏/);
  assert.match(app, /整组提交前不显示答案和中文/);
  assert.match(app, /一段音频，连续听写 10 个词/);
  assert.match(app, /dictation-sequence-player/);
  assert.doesNotMatch(app, /dictation-group-tabs|场景听写分组/);
  assert.doesNotMatch(styles, /\.dictation-group-tabs/);
  assert.match(app, /toggleDictationSequence/);
  assert.match(app, /seekDictationSequence/);
  assert.match(app, /拖动场景听写进度/);
  assert.match(app, /一段音频，连续听写 \{groupPhrases\.length\} 个词组/);
  assert.match(app, /间隔约 4 秒/);
  assert.match(app, /拖动吞音词组听写进度/);
  assert.match(app, /一次提交本组 \{groupPhrases\.length\} 个词组/);
  assert.match(app, /每个词后预留约 4 秒书写时间/);
  assert.doesNotMatch(app, /playDictationWord|播放当前词|自动播放下一词/);
  assert.match(app, /一次提交本组 \{dictationWords\.length\} 词/);
  assert.match(app, /moveToNextDictationInput/);
  assert.match(app, /wrongWords\.forEach/);
  assert.match(styles, /\.dictation-batch-list/);
  assert.match(styles, /\.dictation-batch-footer/);
  assert.match(styles, /\.dictation-sequence-player/);
  assert.match(app, /先核对中文含义/);
  assert.match(app, /核对后再次出现/);
  assert.match(app, /核对后很快再现/);
  assert.match(app, /repeatGap/);
  assert.match(app, /今日到期复习/);
  assert.match(app, /我的笔记/);
  assert.doesNotMatch(app, /加入错题本/);
  assert.doesNotMatch(app, /question-note-button/);
  assert.match(app, /加入笔记/);
  assert.match(app, /toggleNotebookEntry/);
  assert.match(app, /buildOfficialQuestionNote/);
  assert.match(app, /enrichLegacyOfficialNotebookEntry/);
  assert.match(app, /readingNotebookReview/);
  assert.match(app, /sourceLabel = "原文对应段"/);
  assert.match(app, /matchingParagraph\?\.text/);
  assert.match(app, /readingSource\.includes\("reading"\)/);
  assert.match(app, /每日训练 · 阅读/);
  assert.match(app, /listeningNotebookReview/);
  assert.match(app, /officialAnswerAudioMedia/);
  assert.match(app, /所在完整 Task 音频/);
  assert.doesNotMatch(app, /segmentIndex: Math\.max\(0, answers\.findIndex/);
  assert.match(app, /答案与易混淆音频/);
  assert.match(app, /播放听力片段/);
  assert.match(app, /"▶ 播放"/);
  assert.doesNotMatch(app, /播放 Q\$\{context\.questionNumber\} 答案与易混淆语境/);
  assert.doesNotMatch(app, /只回听这道题答案出现前后的片段/);
  assert.match(app, /notebookListeningSelections/);
  assert.match(app, /notebook-listening-options/);
  assert.match(app, /输入你的答案/);
  assert.match(app, /!readingReview && !listeningReview && <h2>/);
  assert.match(app, /segmentDuration/);
  assert.match(app, /readingQuestionOptions/);
  assert.doesNotMatch(app, /notebookOptionMatchesAnswer/);
  assert.doesNotMatch(app, /我的选择/);
  assert.match(app, /notebookDetailForDisplay/);
  assert.match(app, /我的答案\|我的作答\|我的回答/);
  assert.match(app, /notebookListeningInputs\[entry\.id\] \?\? ""/);
  assert.match(app, /revealedNotebookAnswerIds/);
  assert.match(app, /expandedNotebookIds/);
  assert.match(app, /type NotebookCategory = "all" \| "word" \| "listening" \| "reading" \| "speaking" \| "writing" \| "other"/);
  assert.match(app, /notebookEntryCategory/);
  assert.match(app, /notebookCategoryLabels/);
  assert.match(app, /notebook-category-tabs/);
  assert.match(app, /按科目筛选笔记/);
  assert.match(app, /visibleNotebookEntries/);
  assert.match(app, /notebook-entry-toggle/);
  assert.match(app, /notebook-entry-preview/);
  assert.match(app, /aria-expanded=\{expanded\}/);
  assert.match(app, /\{expanded \? "收起" : "展开"\}/);
  assert.match(app, /点击显示正确答案/);
  assert.match(app, /原文对应句/);
  assert.doesNotMatch(app, /<article><span>我的作答<\/span>/);
  assert.match(styles, /\.notebook-reading-review \.is-correct-answer button/);
  assert.doesNotMatch(styles, /\.notebook-reading-review \.is-options li\.is-user-answer/);
  assert.match(styles, /\.notebook-listening-review \.is-audio button/);
  assert.match(styles, /\.notebook-audio-scrubber input/);
  assert.match(styles, /\.notebook-listening-options button\.is-selected/);
  assert.match(styles, /\.notebook-entry\.is-collapsed/);
  assert.match(styles, /\.notebook-entry-preview/);
  assert.match(styles, /\.notebook-category-tabs/);
  assert.match(styles, /\.notebook-list \{[^}]*align-items:start/);
  assert.match(styles, /\.notebook-kind\.listening/);
  assert.match(styles, /\.notebook-kind\.reading/);
  assert.match(app, /dailyDifficultyProfileForDate/);
  assert.doesNotMatch(app, /dailyDifficultyProfiles/);
  assert.match(state, /export type DailyDifficultyBand = 6 \| 7 \| 8/);
  assert.match(state, /export type DailyDifficultyStage = 1 \| 2 \| 3 \| 4/);
  assert.match(state, /targetDailyDifficultyBand/);
  assert.match(state, /dailyDifficultyProfileForDate/);
  assert.match(state, /target <= 6/);
  assert.match(state, /target <= 7/);
  assert.match(state, /stageLabels/);
  assert.match(state, /progressRatio \* rateIncrease/);
  assert.match(state, /base\.reading\.minutes - progressRatio/);
  assert.match(state, /base\.speaking\.minimumWords \+ progressRatio/);
  assert.match(state, /10 题连续作答/);
  assert.match(state, /Academic Passage 模式/);
  assert.match(state, /Speaking Part 3 模式/);
  assert.match(dailyPractice, /difficultyRotationIndex/);
  assert.match(dailyPractice, /getDailyListeningExercise\(dayKey: string, band:/);
  assert.match(dailyPractice, /getDailyReadingExercise\(dayKey: string, band:/);
  assert.match(dailyPractice, /getDailySpeakingScenario\(dayKey: string, band:/);
  assert.match(app, /getDailyListeningExercise\(exerciseDate, difficulty\.band\)/);
  assert.match(app, /getDailyReadingExercise\(exerciseDate, difficulty\.band\)/);
  assert.match(app, /getDailySpeakingScenario\(exerciseDate, difficulty\.band\)/);
  assert.doesNotMatch(app, /PERSONALISED DAILY DIFFICULTY|daily-difficulty-panel|daily-difficulty-progress|daily-difficulty-ladder|daily-exam-format/);
  assert.doesNotMatch(app, /IELTS LISTENING FORMAT/);
  assert.doesNotMatch(app, /reading-difficulty-brief/);
  assert.match(app, /IELTS ACADEMIC READING FORMAT/);
  assert.match(app, /IELTS SPEAKING FORMAT/);
  assert.match(app, /Band \{difficulty\.band\}\.0 训练语速/);
  assert.match(app, /difficulty\.reading\.minutes/);
  assert.match(app, /difficulty\.speaking\.minimumWords/);
  assert.match(app, /daily-reading-timer/);
  assert.match(app, /questionForDifficulty/);
  assert.match(app, /requireCounterpoint/);
  assert.doesNotMatch(styles, /\.daily-difficulty-panel|\.daily-difficulty-progress|\.daily-difficulty-ladder|\.daily-exam-format/);
  assert.match(styles, /\.exam-format-strip/);
  assert.match(styles, /\.daily-reading-timer/);
  assert.match(app, /题目位置：题册 P/);
  assert.match(app, /原文依据：/);
  assert.match(app, /officialQuestionMedia/);
  assert.match(app, /officialQuestionReference/);
  assert.match(app, /notebook-entry-reference/);
  assert.match(styles, /\.notebook-entry-reference iframe/);
  assert.match(app, /PERSONAL KNOWLEDGE BASE/);
  assert.match(app, /我的单词本/);
  assert.match(app, /IELTS LEARNING LIBRARY/);
  assert.match(app, /搜索单词本，也可以查询词库外单词/);
  assert.match(app, /语境例句/);
  assert.match(app, /inferPartOfSpeech/);
  assert.match(app, /wordbookEntries/);
  assert.match(state, /export type PersonalWordbookEntry/);
  assert.match(state, /personalWordbook: PersonalWordbookEntry\[\]/);
  assert.match(state, /personalWordbook: \[\]/);
  assert.match(state, /Array\.isArray\(stored\.personalWordbook\)/);
  assert.match(app, /addDictionaryResultToWordbook/);
  assert.match(app, /dictionaryContextExample/);
  assert.match(app, /语境例句/);
  assert.match(app, /开放词典未提供原例句，当前为辅助理解句/);
  assert.match(app, /英文释义与更多例句/);
  assert.match(app, /\+ 加入单词本/);
  assert.match(app, /✓ 已在单词本/);
  assert.match(app, /我的添加 \{personalEntries\.length\}/);
  assert.match(app, /自行添加 · 全英语词典/);
  assert.match(app, /查询全部英语单词/);
  assert.match(app, /searchAllEnglishWords/);
  assert.match(app, /wordbook-global-results/);
  assert.match(app, /输入词库外英文后，按 Enter 即可在本页查看结果/);
  assert.match(app, /api\.mymemory\.translated\.net\/get/);
  assert.match(styles, /\.wordbook-global-results/);
  assert.match(styles, /button\.is-in-wordbook/);
  assert.match(styles, /\.dictionary-example-card/);
  assert.match(styles, /\.wordbook-global-example/);
  assert.match(app, /DictionarySearchDialog/);
  assert.match(app, /开放英语词典/);
  assert.match(app, /findLocalDictionaryEntries/);
  assert.match(app, /查单词与中文释义/);
  assert.match(app, /本地 3,600 词使用现有中文词库/);
  assert.match(app, /单词本 ·/);
  assert.match(app, /每日学习记录/);
  assert.match(app, /继续增加学习/);
  assert.doesNotMatch(app, /className="daily-word-row"/);
  assert.doesNotMatch(app, /className="practice-grid"|className="practice-card"/);
  assert.match(app, /function AiTutorView/);
  assert.match(app, /aria-label="打开 IELTS AI 助教" onClick=\{\(\) => onNavigate\("scene"\)\}/);
  assert.doesNotMatch(app, /aria-label="试听场景"/);
  assert.match(app, /buildTutorReply/);
  assert.match(app, /detectTutorTopic/);
  assert.match(app, /extractTutorVocabularyTerms/);
  assert.match(app, /previousQuestion/);
  assert.match(app, /不会猜题/);
  assert.match(app, /不想在不相关领域给你一个看似确定但可能错误的答案/);
  assert.match(app, /回答范围 ·/);
  assert.match(app, /aria-label="向 IELTS AI 提问"/);
  assert.match(app, /function AiTutorView/);
  assert.match(app, /tutorRecognition/);
  assert.match(app, /webkitSpeechRecognition/);
  assert.match(app, /aria-label=\{voiceState === "listening" \? "停止语音输入" : "开始语音输入"\}/);
  assert.match(app, /识别完成，请检查文字后发送/);
  assert.match(app, /没有获得麦克风权限/);
  assert.match(app, /基于内置备考知识与当前学习进度/);
  assert.match(styles, /white-space:pre-line/);
  assert.match(styles, /\.ai-message-topic/);
  assert.match(styles, /\.ai-voice-input\.is-listening/);
  assert.doesNotMatch(app, /ai-tutor-progress|<span>今日进度<\/span>/);
  assert.match(app, /profile-water-gauge/);
  assert.match(app, /planProgress\.percent === 0 \? " is-empty"/);
  assert.match(app, /从今天开始/);
  assert.match(styles, /\.profile-water-gauge\.is-empty/);
  assert.match(styles, /\.profile-water-empty/);
  assert.match(app, /profile-water-fill/);
  assert.match(app, /整体备考计划完成度/);
  assert.match(app, /OVERALL PLAN LEVEL/);
  assert.match(app, /目标分数会切换听、读、说的专属难度题库/);
  assert.doesNotMatch(app, /每完成一项今日任务，水位会上升 25%/);
  assert.match(app, /target-band-selector/);
  assert.match(app, /目标分数与备考周期/);
  assert.match(app, /PERSONALISED STUDY PLAN/);
  assert.match(app, /设置目标分数与备考周期/);
  assert.match(app, /自定义学习天数/);
  assert.match(app, /重新生成计划/);
  assert.match(app, /dailyVocabularyTarget\(progress\.studyPlanDays, progress\.targetBandScore\)/);
  assert.match(app, /路线内部再按学习天数逐日递升/);
  assert.match(app, /5\.5–6\.0 使用 Band 6 路线/);
  assert.match(app, /切换后听、读、说题目与每日要求一起改变/);
  assert.match(styles, /\.study-plan-card/);
  assert.match(styles, /\.study-plan-presets/);
  assert.doesNotMatch(app, /study-plan-focus|听力重点|口语重点|阅读重点|写作重点/);
  assert.doesNotMatch(styles, /\.study-plan-focus/);
  assert.doesNotMatch(app, /className="profile-notebook-card"|className="profile-grid"|进入我的笔记 →|onOpenNotebook/);
  assert.doesNotMatch(styles, /\.profile-grid|\.profile-notebook-card/);
  assert.match(app, /完成今日全部训练/);
  assert.match(app, /points: 20/);
  assert.match(app, /完成套题/);
  assert.match(app, /points: 10/);
  assert.match(app, /补完昨日任务/);
  assert.match(app, /points: 5/);
  assert.match(app, /className="profile-water-score-row"/);
  assert.match(app, /className="profile-points-chip"/);
  assert.match(app, /当前共有 \$\{progress\.points\} 积分/);
  assert.match(styles, /\.profile-points-chip/);
  assert.doesNotMatch(app, /POINTS & RANKING|积分排行|体验榜|experienceLeaderboard|rewardLeaderboard|RewardCenterView/);
  assert.doesNotMatch(styles, /\.reward-ranking|\.reward-overview|\.reward-history|\.reward-rules/);
  assert.doesNotMatch(app, /className="profile-rewards-card"|profile-reward-mark/);
  assert.doesNotMatch(styles, /\.profile-rewards-card|\.profile-reward-mark/);
  assert.doesNotMatch(app, /\["今日词汇"|\["待强化词汇"/);
  assert.match(styles, /\.ai-tutor-shell/);
  assert.match(styles, /\.profile-water-gauge/);
  assert.match(styles, /\.profile-water-breakdown/);
  assert.match(styles, /\.target-band-selector/);
  assert.match(styles, /@keyframes profile-wave/);
  assert.match(data, /length: 36/);
  assert.match(data, /expandedVocabularyRows/);
  const curatedVocabularySource = data.match(/const dailyVocabularySource = `([\s\S]*?)`\.trim\(\);/);
  assert.ok(curatedVocabularySource);
  assert.equal(curatedVocabularySource[1].trim().split("\n").length, 300);
  assert.equal((expandedVocabulary.match(/^ {2}\[/gm) ?? []).length, 3300);
  assert.doesNotMatch(expandedVocabulary, /^ {2}\["(?:the|and|of|be)",/gm);
  assert.match(data, /NGSL 1\.2 · CC BY-SA 4\.0/);
  assert.match(data, /NAWL 1\.2 · CC BY-SA 4\.0/);
  assert.match(notices, /New General Service List 1\.2/);
  assert.match(notices, /New Academic Word List 1\.2/);
  assert.match(notices, /ECDICT/);
  assert.match(app, /今天还想多练一点/);
  assert.match(app, /今日基础完成度保持 100%/);
  assert.match(app, /复习错词与笔记/);
  assert.match(app, /进入套题训练/);
  assert.match(app, /有效学习时间与已完成任务/);
  assert.doesNotMatch(app, /有效停留时间|专项停留时间/);
  assert.doesNotMatch(app, /旧版累计|无法可靠拆分到具体日期/);
  assert.match(app, /showStudyHistory/);
  assert.match(app, /最近 7 天学习时间/);
  assert.match(app, /每日学习趋势/);
  assert.match(app, /每月累计学习时间/);
  assert.match(app, /linePoints/);
  assert.match(app, /monthTotals/);
  assert.match(styles, /\.study-history-bar-chart/);
  assert.match(styles, /\.study-history-chart-card\.is-line-chart/);
  assert.match(styles, /\.study-history-chart-card\.is-monthly-chart/);
  assert.match(styles, /\.extra-study-panel/);
  assert.match(styles, /\.extra-study-options/);
  assert.match(styles, /\.profile-wordbook/);
  assert.match(styles, /\.profile-overview-column>\.profile-wordbook/);
  assert.match(styles, /\.wordbook-list/);
  assert.match(styles, /\.wordbook-entry/);
  assert.match(styles, /\.wordbook-entry-actions/);
  const wordbookPosition = app.indexOf('className="profile-wordbook"');
  const streakPosition = app.indexOf('className="profile-streak-card"');
  assert.ok(wordbookPosition > -1 && wordbookPosition < streakPosition, "wordbook should appear before the streak card");
  assert.equal((app.match(/className="profile-wordbook"/g) ?? []).length, 1, "wordbook entry should render once");
  assert.match(styles, /\.topbar-dictionary-search/);
  assert.match(styles, /\.dictionary-search-dialog/);
  assert.match(styles, /\.dictionary-local-results/);
  assert.match(app, /confusingWordGroups/);
  assert.match(app, /ConfusingWords word=\{entry\.word\}/);
  assert.match(styles, /\.wordbook-confusable/);
  assert.doesNotMatch(data, /In context,/);
  const dictionaryRoute = await readFile(new URL("../app/api/dictionary/route.ts", import.meta.url), "utf8");
  assert.match(dictionaryRoute, /api\.dictionaryapi\.dev/);
  assert.match(dictionaryRoute, /api\.mymemory\.translated\.net/);
  assert.match(dictionaryRoute, /langpair=en%7Czh-CN/);
  assert.match(dictionaryRoute, /AbortSignal\.timeout\(6000\)/);
  assert.match(app, /result\.chineseMeaning/);
  assert.match(app, /中文翻译暂时不可用/);
  assert.match(styles, /\.dictionary-chinese-meaning/);
  assert.match(app, /readingSourceEvidence/);
  assert.match(data, /readingReviewEvidence/);
  assert.match(app, /荧光笔标注原文/);
  assert.match(app, /reading-answer-analysis/);
  assert.match(styles, /\.reading-paragraphs mark/);
  assert.match(app, /荧光笔定位原文/);
  assert.doesNotMatch(app, /official-reading-evidence/);
  assert.doesNotMatch(app, /HIGHLIGHTED SOURCE|原文荧光定位/);
  assert.match(app, /official-reading-passage-page-/);
  assert.match(app, /scrollIntoView\(\{ behavior: "smooth", block: "center" \}\)/);
  assert.doesNotMatch(app, /activeReadingSearchText|&search=/);
  assert.match(app, /readingSourceHighlights/);
  assert.match(app, /official-reading-highlight-layer/);
  assert.match(app, /official-reading-highlight-\$\{questionNumber\}-0/);
  assert.match(app, /✓ 已在原文标出/);
  assert.doesNotMatch(styles, /\.official-reading-evidence/);
  assert.doesNotMatch(styles, /\.official-pdf-page-lock\.is-evidence-page/);
  assert.match(styles, /\.official-reading-highlight-layer i/);
  assert.match(app, /NOT GIVEN 核验范围/);
  assert.match(app, /readingAnalysisMethod/);
  assert.match(app, /fullyCompleted/);
  assert.doesNotMatch(app, /if \(answeredCount < 10\) return/);
  assert.match(app, /提交当前答案（\$\{answeredCount\}\/10）/);
  assert.match(app, /const redoListening = \(\) =>/);
  assert.match(app, /setFormAnswers\(\{\}\)/);
  assert.match(app, /setSelectedFacilities\(\[\]\)/);
  assert.match(app, /setMatchingAnswers\(\{\}\)/);
  assert.match(app, /setChoiceAnswers\(\{\}\)/);
  assert.match(app, /↺ 再写一遍/);
  assert.match(app, /renderListeningAnalysis/);
  assert.match(app, /renderListeningNoteButton/);
  assert.match(app, /加入笔记（含答案与易混淆音频）/);
  assert.match(app, /personalisedListeningFeedback/);
  assert.match(app, /isLikelySpellingMistake/);
  assert.match(app, /需要着重加强记住/);
  assert.match(app, /if \(correct\) return <aside className="listening-answer-analysis is-correct">/);
  assert.match(app, /原文定位/);
  assert.match(app, /怎么改进/);
  assert.match(styles, /\.listening-answer-analysis/);
  assert.match(app, /const redoReading = \(\) =>/);
  assert.match(app, /setAnswers\(\{\}\)/);
  assert.match(app, /setActiveReviewId\(null\)/);
  assert.match(app, /onClick=\{redoReading\}>↺ 再写一遍/);
  assert.match(app, /加入笔记（含原文定位）/);
  assert.match(app, /正确答案：\{question\.answers\[0\]\}/);
  assert.match(app, /disabled=\{score === null\}/);
  assert.match(app, /提交后解锁原文/);
  assert.match(app, /听力原文 · 未解锁/);
  assert.match(app, /提交当前答案后即可解锁原文；不要求先答完全部 10 题/);
  assert.match(app, /setShowTranscript\(false\)/);
  assert.doesNotMatch(app, /if \(answeredCount < totalQuestions\) return/);
  assert.match(app, /全部答案和解析已经显示，但本项尚未计为完成/);
  assert.match(app, /官方套题训练计划/);
  assert.doesNotMatch(app, /IELTS 官方公开样题|题目与录音由 IELTS\.org 提供|等待完整提交|个必做 Passage 已提交/);
  const skillOrderBlock = data.match(/export const skills:[\s\S]*?\];/)?.[0] ?? "";
  assert.ok(skillOrderBlock.indexOf('id: "reading"') < skillOrderBlock.indexOf('id: "speaking"'));
  assert.match(app, /开始本套/);
  assert.match(app, /OfficialTestRunner/);
  assert.match(app, /⌂ 返回首页/);
  assert.match(app, /onHome=\{\(\) => setView\("today"\)\}/);
  assert.match(styles, /\.official-runner-nav button\.is-home/);
  assert.match(app, /IELTS-OFFICIAL-AR-MLP-01/);
  assert.match(app, /Passage 1 · Questions 1–13/);
  assert.match(app, /Passage 2 · Questions 14–26/);
  assert.match(app, /Passage 3 · Questions 27–40/);
  assert.match(app, /modified-large-print-question-booklet\.pdf/);
  assert.match(app, /modified-large-print-text-booklet\.pdf/);
  assert.match(app, /modified-large-print-sample-test-answer-key\.pdf/);
  assert.doesNotMatch(app, /readingQuestionTypeMaterial|ielts-academic-reading-sample-tasks-2023\.pdf/);
  const fullReadingBlock = app.match(/const readingMaterial:[\s\S]*?const writingMaterial:/)?.[0] ?? "";
  const fullReadingNumbers = [...fullReadingBlock.matchAll(/number: "(\d+)"/g)].map((match) => Number(match[1]));
  assert.deepEqual(fullReadingNumbers, Array.from({ length: 40 }, (_, index) => index + 1));
  assert.equal((fullReadingBlock.match(/explanation: "/g) ?? []).length, 40);
  assert.equal((fullReadingBlock.match(/id: "reading-passage-/g) ?? []).length, 3);
  assert.match(fullReadingBlock, /questionPages: \[4, 5, 6\], passagePages: \[2, 3, 4\]/);
  assert.match(fullReadingBlock, /questionPages: \[11, 12, 13, 14\], passagePages: \[9, 10, 11, 12\]/);
  assert.doesNotMatch(fullReadingBlock, /passagePages: \[9, 10, 11, 12, 13/);
  assert.match(app, /ielts-listening-sample-tasks-2023\.pdf/);
  const listeningBlock = app.match(/const listeningMaterial:[\s\S]*?const readingMaterial:/)?.[0] ?? "";
  assert.equal([...listeningBlock.matchAll(/number: "\d+"/g)].length, 44);
  assert.deepEqual([...listeningBlock.matchAll(/transcriptPage: (\d+)/g)].map((match) => Number(match[1])), [4, 9, 12, 15, 19, 23, 27, 31]);
  assert.match(listeningBlock, /questionPages: \[29, 30\], transcriptPage: 31, transcriptPages: \[31, 32\]/);
  assert.equal((listeningBlock.match(/questionPages: \[/g) ?? []).length, 8);
  assert.equal((listeningBlock.match(/transcriptPages: \[/g) ?? []).length, 8);
  assert.match(app, /material\.tasks\.length > 1/);
  assert.match(app, /official-task-map/);
  assert.match(app, /official-source-document/);
  assert.doesNotMatch(app, /内容来源说明|official-source-note/);
  assert.doesNotMatch(styles, /\.official-source-note/);
  assert.match(app, /材料区 \+ 答题区模板/);
  assert.match(app, /isolateOfficialTaskPages/);
  assert.match(app, /当前 Task 独立显示/);
  assert.match(app, /officialTaskPaperPages\.map/);
  assert.match(app, /task\.transcriptPages \?\? \[task\.transcriptPage\]/);
  assert.match(app, /toolbar=0&navpanes=0&scrollbar=0&view=Fit/);
  assert.match(app, /提交后只解锁本 Task 的听力原文/);
  assert.match(app, /task\.transcriptPage && !taskSubmitted/);
  assert.match(app, /task\.transcriptPage && taskSubmitted/);
  assert.match(app, /听力原文尚未开放/);
  assert.match(app, /8 INDEPENDENT LISTENING TASKS/);
  assert.match(app, /可以提前提交查看当前 Task 的答案和原文/);
  assert.match(app, /officialTaskRecordId/);
  assert.match(app, /officialTaskResults/);
  assert.match(app, /redoCurrentTask/);
  assert.match(app, /taskAttemptVersions/);
  assert.match(app, /is-fresh-attempt/);
  assert.match(app, /setActiveReadingQuestion\(null\)/);
  assert.match(app, /officialTaskAttemptHistory/);
  assert.match(app, /再做一次/);
  assert.match(app, /查看历史答案/);
  assert.match(app, /第 \{attemptIndex \+ 1\} 次作答/);
  assert.doesNotMatch(app, />修改答案</);
  assert.match(app, /当前独立 Task 的官方录音/);
  assert.match(app, /Official Academic Writing Sample Test 2023/);
  assert.match(app, /IELTS-OFFICIAL-AW-2023-01/);
  assert.match(app, /minimumWords: 150/);
  assert.match(app, /minimumWords: 250/);
  const writingBlock = app.match(/const writingMaterial:[\s\S]*?const speakingMaterial:/)?.[0] ?? "";
  assert.match(writingBlock, /questionPages: \[3\], answerPage: 9, answerLabel: "查看本 Task 电子范文与解析"/);
  assert.match(writingBlock, /questionPages: \[6\], answerPage: 18, answerLabel: "查看本 Task 电子范文与解析"/);
  assert.equal((writingBlock.match(/electronicModel: \{/g) ?? []).length, 2);
  assert.match(app, /ELECTRONIC MODEL ANSWER/);
  assert.match(app, /清晰电子稿/);
  assert.match(app, /并非对官方手写考生稿的逐字转录/);
  assert.match(app, /task\.electronicModel\.paragraphs\.map/);
  assert.match(app, /task\.electronicModel\.analysis\.map/);
  assert.match(styles, /\.official-writing-model>article/);
  assert.match(app, /analyzeWritingResponse/);
  assert.match(app, /WritingFeedbackPanel/);
  assert.match(app, /PERSONALISED WRITING REVIEW/);
  assert.match(app, /根据本次作文生成的改进建议/);
  assert.match(app, /Task 1 缺少清晰总览/);
  assert.match(app, /Task 2 引言中的立场不够明确/);
  assert.match(app, /重复较明显的词/);
  assert.match(app, /根据建议继续修改/);
  assert.match(app, /用户原文逐句标注/);
  assert.match(app, /buildWritingAnnotations/);
  assert.match(app, /长句需要拆分/);
  assert.match(app, /改写例句/);
  assert.match(app, /Task 2 观点、论证与例证建议/);
  assert.match(styles, /\.official-writing-annotated mark\.is-good/);
  assert.match(styles, /\.official-writing-annotated mark\.needs-work/);
  assert.match(styles, /\.official-writing-idea-bank/);
  assert.match(styles, /\.official-writing-feedback-metrics/);
  assert.match(app, /2 INDEPENDENT WRITING TASKS/);
  assert.match(app, /每个 Writing Task 独立保存作文与完成状态/);
  assert.match(app, /提交后只解锁本 Task 的范文与考官评语/);
  assert.match(app, /COMPUTER-DELIVERED WRITING/);
  assert.match(app, /提交本 Task/);
  assert.doesNotMatch(app, /materials: \[listeningMaterial, readingMaterial, writingMaterial\]/);
  assert.match(app, /ielts-speaking-part-3-sample-recording\.mp3/);
  assert.match(app, /id: "speaking-review"[\s\S]*?duration: "25 分钟", durationMinutes: 25/);
  assert.doesNotMatch(app, /duration: "55 分钟", durationMinutes: 55/);
  const speakingBlock = app.match(/const speakingMaterial:[\s\S]*?const officialTestSchedule:/)?.[0] ?? "";
  assert.equal((speakingBlock.match(/speakingPrompt: \{/g) ?? []).length, 3);
  assert.match(speakingBlock, /What kind of place is it\?/);
  assert.match(speakingBlock, /Describe something you own which is very important to you\./);
  assert.match(speakingBlock, /What kind of things give status to people in your country\?/);
  assert.equal((speakingBlock.match(/preparationSeconds: 60/g) ?? []).length, 3);
  assert.match(app, /3 INDEPENDENT SPEAKING PARTS/);
  assert.match(app, /material\.tasks\.length > 1 && \(/);
  assert.doesNotMatch(app, /material\.tasks\.length > 1 && !speakingTaskMode/);
  assert.match(app, /is-speaking-workspace/);
  assert.match(app, /\(!speakingTaskMode \|\| taskSubmitted\) && <div className="official-material-column">/);
  assert.match(app, /OfficialSpeakingResponse/);
  assert.match(app, /COMPUTER-DELIVERED SPEAKING PRACTICE/);
  assert.match(app, /考官提问 → 准备 → 录音 → 提交；回答后继续追问/);
  assert.match(app, /navigator\.mediaDevices\?\.getUserMedia/);
  assert.match(app, /new MediaRecorder\(stream\)/);
  assert.match(app, /recorder\.pause\(\)/);
  assert.match(app, /recorder\.resume\(\)/);
  assert.match(app, /new AudioContext\(\)/);
  assert.match(app, /PERSONALISED SPEAKING REVIEW/);
  assert.match(app, /TOPIC TEMPLATE/);
  assert.match(app, /TARGETED VOICE PRACTICE/);
  assert.match(app, /回答完成后生成的语音不足与改进建议/);
  assert.match(app, /加入笔记（含考官语音）/);
  assert.match(app, /playNotebookMedia/);
  assert.match(app, /media\.endSeconds/);
  assert.match(app, /enrichDailyListeningNotebookEntry/);
  assert.match(app, /completeListeningCue/);
  assert.match(app, /包含题目前后语境、干扰项、纠正信息与最终答案/);
  assert.match(app, /cue\.startSeconds - 3\.2/);
  assert.match(app, /cue\.endSeconds \+ 4/);
  assert.match(app, /易混淆点：/);
  assert.match(app, /submitted && <section className="speaking-topic-template"/);
  assert.match(app, /!speakingTaskMode \|\| taskSubmitted/);
  assert.match(app, /REVIEW MATERIAL LOCKED/);
  assert.match(app, /提交本 Part 后，才会显示语音不足分析、针对性改进练习、话题模板/);
  assert.match(app, /const allQuestions = \[prompt\.examinerQuestion, \.\.\.prompt\.supportingQuestions\]/);
  assert.match(app, /questionIndex < allQuestions\.length - 1/);
  assert.match(app, /buildAdaptiveSpeakingFollowUp/);
  assert.match(app, /const nextQuestion = buildAdaptiveSpeakingFollowUp\(task\.id, transcript/);
  assert.match(app, /playExaminerQuestion\(nextQuestion\)/);
  assert.match(app, /EXAMINER FOLLOW-UP/);
  assert.match(app, /followUpMode: "answer-aware"/);
  assert.match(app, /提交本题，听下一问/);
  assert.match(app, /提交最后一题并生成反馈/);
  assert.match(app, /turnCount: String\(completedTurns\.length\)/);
  assert.doesNotMatch(app, /本 Part 问题进度|speaking-question-progress|speaking-adaptive-badge/);
  assert.match(app, /不能可靠判断单个音素是否准确/);
  assert.match(app, /正式 Part 2 会给 1 分钟准备/);
  assert.match(styles, /\.official-speaking-response/);
  assert.match(styles, /\.official-standard-paper-body\.is-speaking-workspace>\.official-speaking-response \{ width:min\(100%,720px\); max-width:720px; max-height:none/);
  assert.match(styles, /\.speaking-prep-panel/);
  assert.match(styles, /\.speaking-improvement-drills/);
  assert.doesNotMatch(styles, /\.speaking-question-progress|\.speaking-adaptive-badge/);
  assert.match(styles, /\.official-speaking-material-lock/);
  assert.match(styles, /\.speaking-transcript-highlight mark\.is-good/);
  assert.match(app, /official-paper-frame/);
  assert.match(app, /workspace is-official-test/);
  assert.match(styles, /\.workspace\.is-official-test/);
  assert.match(styles, /grid-template-columns:minmax\(0,1\.5fr\) minmax\(300px,\.72fr\)/);
  assert.match(app, /is-listening-workspace/);
  assert.match(app, /is-writing-workspace/);
  assert.match(app, /official-material-column/);
  assert.match(styles, /\.official-standard-paper-body\.is-listening-workspace,\.official-standard-paper-body\.is-writing-workspace \{ grid-template-columns:minmax\(0,1\.5fr\) minmax\(300px,\.72fr\)/);
  assert.match(styles, /\.official-standard-paper-body\.is-listening-workspace>\.official-material-column,\.official-standard-paper-body\.is-writing-workspace>\.official-material-column \{ max-height:calc\(100vh - 24px\)/);
  assert.match(app, /#page=\$\{displayPage\}/);
  assert.match(app, /questionPage/);
  assert.match(app, /answerPage/);
  assert.match(app, /查看答案/);
  assert.match(app, /3 INDEPENDENT READING PASSAGES/);
  assert.match(app, /可以提前提交查看当前 Passage 的答案与解析/);
  assert.match(app, /officialPracticeRecordId/);
  assert.match(app, /allRequiredCompleted/);
  assert.match(app, /officialTaskResultIsComplete/);
  assert.match(app, /requiredTasks\.every/);
  assert.doesNotMatch(app, /markComplete|完成整套后记录/);
  assert.match(app, /COMPUTER-DELIVERED ANSWER SHEET/);
  assert.match(app, /提交当前答案/);
  assert.match(app, /空题按未答处理/);
  assert.match(app, /本次不计为完成，但全部答案已经显示/);
  assert.match(app, /正确答案：/);
  assert.match(app, /answer\.explanation/);
  assert.match(app, />判断依据</);
  assert.match(app, /固定在右侧 · 可独立滚动完成当前 Passage 全部题目/);
  assert.match(styles, /\.official-full-reading-body>\.official-answer-sheet \{ max-height:calc\(100vh - 24px\); overflow-y:auto; position:sticky/);
  assert.match(styles, /\.official-reading-booklet \{ min-width:0; max-height:calc\(100vh - 24px\)/);
  assert.match(styles, /\.official-full-reading-body>\.official-answer-sheet>footer \{[^}]*position:sticky; bottom:-15px/);
  assert.match(styles, /\.official-answer-sheet\.is-fresh-attempt \.official-answer-grid>\.official-answer-item \{ border-color:#e6e1e7; background:white/);
  assert.match(styles, /\.reading-questions \{ position:sticky/);
  assert.match(styles, /@media \(max-width:680px\)/);
  assert.match(app, /仅显示当前 Passage/);
  assert.match(app, /只包含本 Passage 的题目页/);
  assert.doesNotMatch(app, /readingBookletView|文章册与题册切换/);
  assert.doesNotMatch(app, /题目直接在这里|本套材料|本材料任务|Academic Reading · Full Test 1–40|runner-material-index/);
  assert.doesNotMatch(app, /official-task-controls|official-paper-switch|showTaskSelector|<label>选择 \{taskUnitLabel\}|选择 Passage|选择 Task|选择 Part|查看题目 · P|提交后查看答案/);
  assert.doesNotMatch(styles, /\.official-task-controls|\.official-paper-switch/);
  assert.match(app, /officialAnswerIsCorrect/);
  assert.match(app, /new Set\(groupResponses\)/);
  assert.match(app, /ROLLED OVER FROM YESTERDAY/);
  assert.match(app, /昨日未完成/);
  assert.match(app, /progress\.carryoverTasks\.length > 0 &&/);
  assert.match(app, /progress\.carryoverTaskDates\[skillId\]/);
  assert.match(app, /contentDate=\{contentDate\}/);
  assert.match(app, /getDailyVocabulary\(contentDate/);
  assert.match(app, /getDailyListeningVocabulary\(contentDate/);
  assert.match(app, /YESTERDAY&apos;S TASK/);
  assert.match(styles, /\.carryover-context-banner/);
  assert.match(app, /className="daily-training-nav"/);
  assert.match(app, /每日雅思训练页面导航/);
  assert.match(app, /onHome={\(\) => setView\("today"\)\}/);
  assert.match(styles, /\.daily-training-nav button/);
  assert.doesNotMatch(app, /TASK ROLLOVER|目前没有昨日待补做任务|carryover-strip is-empty/);
  assert.match(app, /carryoverTasks\.filter/);
  assert.match(data, /vocabulary|listening|speaking|reading/);
  assert.match(state, /completionPercent/);
});

test("shows the signed-in avatar and name outside the Today homepage", async () => {
  const [app, styles] = await Promise.all([
    readFile(new URL("../app/IeltsApp.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.match(app, /className={`global-account-badge/);
  assert.match(app, /view !== "today" && <button/);
  assert.match(app, /has-account-badge/);
  assert.match(app, /authUser\.displayName/);
  assert.match(app, /authUser\.avatarUrl/);
  assert.match(app, /setView\("profile"\)/);
  assert.doesNotMatch(app, /profile-button[^\n]*>LI</);
  assert.match(styles, /\.global-account-badge/);
  assert.match(styles, /position:fixed/);
});

test("ships no-account local profile onboarding and score planning", async () => {
  const [flow, avatars, app, styles] = await Promise.all([
    readFile(new URL("../app/AuthFlow.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/AccountAvatar.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/IeltsApp.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.doesNotMatch(flow, /手机号|Email|邮箱验证码|密码|注册并|验证并登录|auth-shell|\/api\/auth/);
  assert.match(flow, /无需注册或登录/);
  assert.match(flow, /选择目标分数/);
  assert.match(flow, /5\.5, 6, 6\.5, 7, 7\.5, 8, 8\.5/);
  assert.match(flow, /设置你的头像、名字与目标/);
  assert.match(flow, /按学习天数/);
  assert.match(flow, /输入考试日期/);
  assert.match(flow, /type="date"/);
  assert.match(flow, /daysUntilDate/);
  assert.match(avatars, /accountAvatarPresets/);
  assert.equal((avatars.match(/id: "preset:/g) ?? []).length, 6);
  assert.match(app, /profileStorageKey = "ielts-pass-local-profile-v1"/);
  assert.match(app, /function readLocalProfile/);
  assert.match(app, /provider: "guest"/);
  assert.match(app, /localStorage\.setItem\(profileStorageKey/);
  assert.doesNotMatch(app, /\/api\/auth\?action=session|action: "logout"|退出登录/);
  assert.match(app, /无需登录；头像、名字、目标、笔记与进度保存在当前设备/);
  assert.match(styles, /\.onboarding-progress i \{ width:100%;/);
});

test("includes the finished social preview and removes starter preview files", async () => {
  const image = new URL("../public/og.png", import.meta.url);
  const listeningAudio = new URL("../public/listening-section-1.wav", import.meta.url);
  const artsCentreAudio = new URL("../public/listening-arts-centre.wav", import.meta.url);
  const wildlifeAudio = new URL("../public/listening-wildlife-volunteer.wav", import.meta.url);
  await access(image);
  assert.ok((await stat(image)).size > 100_000);
  await access(listeningAudio);
  assert.ok((await stat(listeningAudio)).size > 1_000_000);
  await access(artsCentreAudio);
  assert.ok((await stat(artsCentreAudio)).size > 1_000_000);
  await access(wildlifeAudio);
  assert.ok((await stat(wildlifeAudio)).size > 1_000_000);
  await assert.rejects(access(new URL("../app/_sites-preview/SkeletonPreview.tsx", import.meta.url)));
});
