import assert from "node:assert/strict";
import { access, readFile, stat } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("https://ielts-ai.test/", { headers: { accept: "text/html", host: "ielts-ai.test" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the IELTS AI product shell and metadata", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<title>IELTS AI/);
  assert.match(html, /场景化雅思学习/);
  assert.match(html, /IELTS AI/);
  assert.match(html, /一轮雅思训练/);
  assert.match(html, /每日 100 词/);
  assert.doesNotMatch(html, /codex-preview|SkeletonPreview|Your site is taking shape|react-loading-skeleton/i);
});

test("ships all four learning modes and persistent progress", async () => {
  const [app, data, state, styles] = await Promise.all([
    readFile(new URL("../app/IeltsApp.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/learning-data.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/learning-state.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  for (const feature of ["VocabularyPractice", "ListeningPractice", "SpeakingPractice", "ReadingPractice", "ReviewView"]) {
    assert.match(app, new RegExp(feature));
  }
  assert.match(app, /localStorage\.setItem/);
  assert.match(app, /document\.visibilityState === "visible"/);
  assert.match(app, /visibilitychange/);
  assert.match(app, /pagehide/);
  assert.match(app, /unsavedSeconds >= 10/);
  assert.match(app, /页面在前台可见时累计学习时间/);
  assert.match(app, /SpeechSynthesisUtterance/);
  assert.match(app, /DailyVocabularySprint/);
  assert.match(app, /Matching Headings|Matching Information|Summary Completion/);
  assert.match(app, /Speaking Part 3|真实考试结构|考官/);
  assert.match(app, /Form Completion|Choose TWO|提交 10 道答案/);
  assert.match(state, /dailyVocabularyDate|dailyVocabularySeen|dailyVocabularyKnown/);
  assert.match(state, /speakingPart3Turns/);
  assert.match(state, /listeningScore/);
  assert.match(state, /localDayKey/);
  assert.match(state, /localWeekKey/);
  assert.match(state, /officialPracticeCompleted/);
  assert.match(state, /DailyStudyRecord/);
  assert.match(state, /dailyStudyHistory/);
  assert.match(state, /recordStudyActivity/);
  assert.match(state, /recordAppStudyTime/);
  assert.match(state, /activeStudySeconds/);
  assert.match(state, /activeSeconds: number/);
  assert.match(state, /id: "app-active-time", label: "App 内有效学习"/);
  assert.match(state, /minutes: Math\.floor\(activeStudySeconds \/ 60\)/);
  assert.doesNotMatch(state, /minutes: 12/);
  assert.match(state, /calculateStudyStreak/);
  assert.match(state, /streak: 0/);
  assert.match(state, /streak: calculateStudyStreak\(dailyStudyHistory, today\)/);
  assert.doesNotMatch(state, /streak: 6/);
  assert.match(state, /OfficialTaskResult/);
  assert.match(state, /officialTaskResults/);
  assert.match(state, /officialTaskAttemptHistory: Record<string, OfficialTaskResult\[\]>/);
  assert.match(state, /carryoverTasks/);
  assert.match(state, /newlyMissedTasks/);
  assert.match(state, /dailyVocabularyCompleted/);
  assert.match(state, /dailyDictationCompleted/);
  assert.match(state, /dailyDictationSeen/);
  assert.match(state, /connectedSpeechSeen/);
  assert.match(state, /dailyVocabularyRatings/);
  assert.match(state, /dailyVocabularyAttempts/);
  assert.match(state, /reviewSchedule/);
  assert.match(state, /NotebookEntry/);
  assert.match(state, /notebook: NotebookEntry\[\]/);
  assert.match(state, /reviewIntervals = \[1, 3, 7, 14, 30, 60\]/);
  assert.match(state, /scheduleWordForReview/);
  assert.match(state, /rateReviewWord/);

  const dailySource = data.match(/const dailyVocabularySource = `([\s\S]*?)`\.trim\(\)/);
  assert.ok(dailySource, "daily vocabulary source should exist");
  const words = dailySource[1].trim().split("\n").map((line) => line.split("|")[0]);
  assert.equal(words.length, 300);
  assert.equal(new Set(words).size, 300);
  assert.match(data, /getDailyVocabulary/);
  assert.match(data, /AWL 学术词族/);
  const listeningSource = data.match(/const listeningVocabularySource = `([\s\S]*?)`\.trim\(\)/);
  assert.ok(listeningSource, "listening vocabulary source should exist");
  const listeningWords = listeningSource[1].trim().split("\n").map((line) => line.split("|")[0]);
  assert.equal(listeningWords.length, 80);
  assert.equal(new Set(listeningWords).size, 80);
  assert.match(data, /matchingHeadings|matchingInformation|trueFalseNotGiven|summary/);
  assert.match(data, /Two-way discussion|questions:/);
  assert.match(data, /formCompletion|multipleSelect|matching|multipleChoice/);
  const connectedSpeechSource = data.match(/export const connectedSpeechPhrases = \[([\s\S]*?)\];/);
  assert.ok(connectedSpeechSource, "connected speech phrase source should exist");
  assert.equal((connectedSpeechSource[1].match(/\{ phrase:/g) ?? []).length, 24);
  assert.match(app, /listening-section-1\.wav/);
  assert.match(app, /listening-scrubber/);
  assert.match(app, /currentTime = nextTime/);
  assert.match(app, /听不懂？显示字幕/);
  assert.match(app, /开始口语模拟/);
  assert.match(app, /记错了/);
  assert.match(app, /重听当前问题/);
  assert.match(app, /继续播放/);
  assert.match(app, /speechSynthesis\.pause/);
  assert.match(app, /speechSynthesis\.resume/);
  assert.match(app, /字幕已隐藏/);
  assert.match(app, /提交检查前不显示中文/);
  assert.match(app, /先核对中文含义/);
  assert.match(app, /核对后再次出现/);
  assert.match(app, /核对后很快再现/);
  assert.match(app, /repeatGap/);
  assert.match(app, /今日到期复习/);
  assert.match(app, /我的笔记/);
  assert.match(app, /加入错题本/);
  assert.match(app, /加入笔记/);
  assert.match(app, /toggleNotebookEntry/);
  assert.match(app, /PERSONAL KNOWLEDGE BASE/);
  assert.match(app, /每日学习记录/);
  assert.match(app, /停留时间与已完成任务/);
  assert.doesNotMatch(app, /旧版累计|无法可靠拆分到具体日期/);
  assert.match(app, /showStudyHistory/);
  assert.match(app, /最近 7 天学习时间/);
  assert.match(app, /每日学习趋势/);
  assert.match(app, /每月累计学习时间/);
  assert.match(app, /linePoints/);
  assert.match(app, /monthTotals/);
  assert.match(styles, /\.study-history-bar-chart/);
  assert.match(styles, /\.study-history-chart-card\.is-line-chart/);
  assert.match(styles, /\.study-history-chart-card\.is-monthly-chart/);
  assert.match(app, /readingSourceEvidence/);
  assert.match(app, /原文荧光定位/);
  assert.match(app, /荧光笔定位原文/);
  assert.match(app, /NOT GIVEN 核验范围/);
  assert.match(app, /readingAnalysisMethod/);
  assert.match(app, /fullyCompleted/);
  assert.match(app, /answeredCount < 10/);
  assert.match(app, /disabled=\{score === null\}/);
  assert.match(app, /提交后解锁原文/);
  assert.match(app, /听力原文 · 未解锁/);
  assert.match(app, /判分前不会显示原文/);
  assert.match(app, /setShowTranscript\(false\)/);
  assert.match(app, /answeredCount < totalQuestions/);
  assert.match(app, /官方套题训练计划/);
  assert.match(app, /IELTS 官方公开样题/);
  assert.match(app, /不等同于已正式考过的 Cambridge 历年原卷/);
  assert.match(app, /开始本套/);
  assert.match(app, /OfficialTestRunner/);
  assert.match(app, /IELTS-OFFICIAL-AR-MLP-01/);
  assert.match(app, /Passage 1 · Questions 1–13/);
  assert.match(app, /Passage 2 · Questions 14–26/);
  assert.match(app, /Passage 3 · Questions 27–40/);
  assert.match(app, /modified-large-print-question-booklet\.pdf/);
  assert.match(app, /modified-large-print-text-booklet\.pdf/);
  assert.match(app, /modified-large-print-sample-test-answer-key\.pdf/);
  assert.doesNotMatch(app, /readingQuestionTypeMaterial|ielts-academic-reading-sample-tasks-2023\.pdf/);
  const fullReadingBlock = app.match(/const readingMaterial:[\s\S]*?const writingMaterial:/)?.[0] ?? "";
  const fullReadingNumbers = [...fullReadingBlock.matchAll(/number: "(\d+)"/g)].map((match) => Number(match[1]));
  assert.deepEqual(fullReadingNumbers, Array.from({ length: 40 }, (_, index) => index + 1));
  assert.equal((fullReadingBlock.match(/explanation: "/g) ?? []).length, 40);
  assert.equal((fullReadingBlock.match(/id: "reading-passage-/g) ?? []).length, 3);
  assert.match(fullReadingBlock, /questionPages: \[4, 5, 6\], passagePages: \[2, 3, 4\]/);
  assert.match(fullReadingBlock, /questionPages: \[11, 12, 13, 14\], passagePages: \[9, 10, 11, 12\]/);
  assert.doesNotMatch(fullReadingBlock, /passagePages: \[9, 10, 11, 12, 13/);
  assert.match(app, /ielts-listening-sample-tasks-2023\.pdf/);
  const listeningBlock = app.match(/const listeningMaterial:[\s\S]*?const readingMaterial:/)?.[0] ?? "";
  assert.equal([...listeningBlock.matchAll(/number: "\d+"/g)].length, 44);
  assert.deepEqual([...listeningBlock.matchAll(/transcriptPage: (\d+)/g)].map((match) => Number(match[1])), [4, 9, 12, 15, 19, 23, 27, 31]);
  assert.match(listeningBlock, /questionPages: \[29, 30\], transcriptPage: 31, transcriptPages: \[31, 32\]/);
  assert.equal((listeningBlock.match(/questionPages: \[/g) ?? []).length, 8);
  assert.equal((listeningBlock.match(/transcriptPages: \[/g) ?? []).length, 8);
  assert.match(app, /material\.tasks\.length > 1/);
  assert.match(app, /official-task-map/);
  assert.match(app, /official-source-document/);
  assert.match(app, /材料区 \+ 答题区模板/);
  assert.match(app, /isolateOfficialTaskPages/);
  assert.match(app, /当前 Task 独立显示/);
  assert.match(app, /officialTaskPaperPages\.map/);
  assert.match(app, /task\.transcriptPages \?\? \[task\.transcriptPage\]/);
  assert.match(app, /toolbar=0&navpanes=0&scrollbar=0&view=Fit/);
  assert.match(app, /提交后只解锁本 Task 的听力原文/);
  assert.match(app, /task\.transcriptPage && !taskSubmitted/);
  assert.match(app, /task\.transcriptPage && taskSubmitted/);
  assert.match(app, /听力原文尚未开放/);
  assert.match(app, /disabled=\{taskRequiresSubmission && !taskSubmitted\}/);
  assert.match(app, /8 INDEPENDENT LISTENING TASKS/);
  assert.match(app, /每个 Task 独立保存答案、得分、完成状态和原文解锁/);
  assert.match(app, /officialTaskRecordId/);
  assert.match(app, /officialTaskResults/);
  assert.match(app, /redoCurrentTask/);
  assert.match(app, /officialTaskAttemptHistory/);
  assert.match(app, /再做一次/);
  assert.match(app, /查看历史答案/);
  assert.match(app, /第 \{attemptIndex \+ 1\} 次作答/);
  assert.doesNotMatch(app, />修改答案</);
  assert.match(app, /当前独立 Task 的官方录音/);
  assert.match(app, /Official Academic Writing Sample Test 2023/);
  assert.match(app, /IELTS-OFFICIAL-AW-2023-01/);
  assert.match(app, /minimumWords: 150/);
  assert.match(app, /minimumWords: 250/);
  const writingBlock = app.match(/const writingMaterial:[\s\S]*?const speakingMaterial:/)?.[0] ?? "";
  assert.match(writingBlock, /questionPages: \[3\], answerPage: 9, answerLabel: "查看本 Task 电子范文与解析"/);
  assert.match(writingBlock, /questionPages: \[6\], answerPage: 18, answerLabel: "查看本 Task 电子范文与解析"/);
  assert.equal((writingBlock.match(/electronicModel: \{/g) ?? []).length, 2);
  assert.match(app, /ELECTRONIC MODEL ANSWER/);
  assert.match(app, /清晰电子稿/);
  assert.match(app, /并非对官方手写考生稿的逐字转录/);
  assert.match(app, /task\.electronicModel\.paragraphs\.map/);
  assert.match(app, /task\.electronicModel\.analysis\.map/);
  assert.match(styles, /\.official-writing-model>article/);
  assert.match(app, /analyzeWritingResponse/);
  assert.match(app, /WritingFeedbackPanel/);
  assert.match(app, /PERSONALISED WRITING REVIEW/);
  assert.match(app, /根据本次作文生成的改进建议/);
  assert.match(app, /Task 1 缺少清晰总览/);
  assert.match(app, /Task 2 引言中的立场不够明确/);
  assert.match(app, /重复较明显的词/);
  assert.match(app, /根据建议继续修改/);
  assert.match(app, /用户原文逐句标注/);
  assert.match(app, /buildWritingAnnotations/);
  assert.match(app, /长句需要拆分/);
  assert.match(app, /改写例句/);
  assert.match(app, /Task 2 观点、论证与例证建议/);
  assert.match(styles, /\.official-writing-annotated mark\.is-good/);
  assert.match(styles, /\.official-writing-annotated mark\.needs-work/);
  assert.match(styles, /\.official-writing-idea-bank/);
  assert.match(styles, /\.official-writing-feedback-metrics/);
  assert.match(app, /2 INDEPENDENT WRITING TASKS/);
  assert.match(app, /每个 Writing Task 独立保存作文与完成状态/);
  assert.match(app, /提交后只解锁本 Task 的范文与考官评语/);
  assert.match(app, /COMPUTER-DELIVERED WRITING/);
  assert.match(app, /提交本 Task/);
  assert.doesNotMatch(app, /materials: \[listeningMaterial, readingMaterial, writingMaterial\]/);
  assert.match(app, /ielts-speaking-part-3-sample-recording\.mp3/);
  assert.match(app, /id: "speaking-review"[\s\S]*?duration: "25 分钟", durationMinutes: 25/);
  assert.doesNotMatch(app, /duration: "55 分钟", durationMinutes: 55/);
  const speakingBlock = app.match(/const speakingMaterial:[\s\S]*?const officialTestSchedule:/)?.[0] ?? "";
  assert.equal((speakingBlock.match(/speakingPrompt: \{/g) ?? []).length, 3);
  assert.match(speakingBlock, /What kind of place is it\?/);
  assert.match(speakingBlock, /Describe something you own which is very important to you\./);
  assert.match(speakingBlock, /What kind of things give status to people in your country\?/);
  assert.equal((speakingBlock.match(/preparationSeconds: 60/g) ?? []).length, 3);
  assert.match(app, /3 INDEPENDENT SPEAKING PARTS/);
  assert.match(app, /OfficialSpeakingResponse/);
  assert.match(app, /COMPUTER-DELIVERED SPEAKING PRACTICE/);
  assert.match(app, /每次提交后考官继续追问；全部回答后才生成反馈/);
  assert.match(app, /navigator\.mediaDevices\?\.getUserMedia/);
  assert.match(app, /new MediaRecorder\(stream\)/);
  assert.match(app, /recorder\.pause\(\)/);
  assert.match(app, /recorder\.resume\(\)/);
  assert.match(app, /new AudioContext\(\)/);
  assert.match(app, /PERSONALISED SPEAKING REVIEW/);
  assert.match(app, /TOPIC TEMPLATE/);
  assert.match(app, /TARGETED VOICE PRACTICE/);
  assert.match(app, /回答完成后生成的语音不足与改进建议/);
  assert.match(app, /submitted && <section className="speaking-topic-template"/);
  assert.match(app, /!speakingTaskMode \|\| taskSubmitted/);
  assert.match(app, /REVIEW MATERIAL LOCKED/);
  assert.match(app, /提交本 Part 后，才会显示语音不足分析、针对性改进练习、话题模板/);
  assert.match(app, /const allQuestions = \[prompt\.examinerQuestion, \.\.\.prompt\.supportingQuestions\]/);
  assert.match(app, /questionIndex < allQuestions\.length - 1/);
  assert.match(app, /buildAdaptiveSpeakingFollowUp/);
  assert.match(app, /const nextQuestion = buildAdaptiveSpeakingFollowUp\(task\.id, transcript/);
  assert.match(app, /playExaminerQuestion\(nextQuestion\)/);
  assert.match(app, /ANSWER-AWARE FOLLOW-UP/);
  assert.match(app, /根据你上一轮的回答追问/);
  assert.match(app, /followUpMode: "answer-aware"/);
  assert.match(app, /提交本题，听下一问/);
  assert.match(app, /提交最后一题并生成反馈/);
  assert.match(app, /turnCount: String\(completedTurns\.length\)/);
  assert.match(app, /本 Part 问题进度/);
  assert.match(app, /不能可靠判断单个音素是否准确/);
  assert.match(app, /正式 Part 2 会给 1 分钟准备/);
  assert.match(styles, /\.official-speaking-response/);
  assert.match(styles, /\.speaking-prep-panel/);
  assert.match(styles, /\.speaking-improvement-drills/);
  assert.match(styles, /\.speaking-question-progress/);
  assert.match(styles, /\.speaking-adaptive-badge/);
  assert.match(styles, /\.official-speaking-material-lock/);
  assert.match(styles, /\.speaking-transcript-highlight mark\.is-good/);
  assert.match(app, /official-paper-frame/);
  assert.match(app, /#page=\$\{displayPage\}/);
  assert.match(app, /questionPage/);
  assert.match(app, /answerPage/);
  assert.match(app, /查看答案/);
  assert.match(app, /3 INDEPENDENT READING PASSAGES/);
  assert.match(app, /每个 Passage 独立保存答案、得分和完成状态/);
  assert.match(app, /officialPracticeRecordId/);
  assert.match(app, /requiredCompletionLabel/);
  assert.match(app, /完成全部 \$\{requiredCompletionLabel\} 后自动记录/);
  assert.doesNotMatch(app, /markComplete|完成整套后记录/);
  assert.match(app, /COMPUTER-DELIVERED ANSWER SHEET/);
  assert.match(app, /提交全部答案/);
  assert.match(app, /正确答案：/);
  assert.match(app, /answer\.explanation/);
  assert.match(app, />判断依据</);
  assert.match(app, /固定在右侧 · 可独立滚动完成当前 Passage 全部题目/);
  assert.match(styles, /\.official-full-reading-body>\.official-answer-sheet \{ max-height:calc\(100vh - 24px\); overflow-y:auto; position:sticky/);
  assert.match(styles, /\.official-reading-booklet \{ min-width:0; max-height:calc\(100vh - 24px\)/);
  assert.match(styles, /\.official-full-reading-body>\.official-answer-sheet>footer \{[^}]*position:sticky; bottom:-15px/);
  assert.match(app, /仅显示当前 Passage/);
  assert.match(app, /只包含本 Passage 的题目页/);
  assert.doesNotMatch(app, /readingBookletView|文章册与题册切换/);
  assert.doesNotMatch(app, /题目直接在这里|本套材料|本材料任务|Academic Reading · Full Test 1–40|runner-material-index/);
  assert.match(app, /official-task-controls is-single/);
  assert.match(app, /officialAnswerIsCorrect/);
  assert.match(app, /new Set\(groupResponses\)/);
  assert.match(app, /ROLLED OVER FROM YESTERDAY/);
  assert.match(app, /昨日未完成/);
  assert.match(app, /carryoverTasks\.filter/);
  assert.match(data, /vocabulary|listening|speaking|reading/);
  assert.match(state, /completionPercent/);
});

test("includes the finished social preview and removes starter preview files", async () => {
  const image = new URL("../public/og.png", import.meta.url);
  const listeningAudio = new URL("../public/listening-section-1.wav", import.meta.url);
  await access(image);
  assert.ok((await stat(image)).size > 100_000);
  await access(listeningAudio);
  assert.ok((await stat(listeningAudio)).size > 1_000_000);
  await assert.rejects(access(new URL("../app/_sites-preview/SkeletonPreview.tsx", import.meta.url)));
});
