// CC0 sentences selected from Tatoeba English sentence export.
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_CC0.tsv.bz2
// Only exact target matches are included; unmatched targets use the app's explicit fallback path.
export const listeningSentenceBank: Record<string, string> = {
  "word:abstract": "Abstract Expressionism is art that shows emotions and ideas through non-representational forms.",
  "word:adult": "Adult cats are the size of human babies.",
  "word:advertisements": "Advertisements for luxury goods are banned and it’s riskier than ever for officials to flaunt their wealth.",
  "word:age": "Age isn't just a number, but it's possible to be in shape at any age.",
  "word:agriculture": "Agriculture in this valley is under another threat. The land, rivers and aquifers under the Valley are drying out. That also affects solar power.",
  "word:aid": "Aid organizations anticipate continued flooding will displace about 200,000 people and affect the lives of 485,000 people.",
  "word:anger": "Anger is there for a reason, but being angry all the time isn't healthy.",
  "word:animal": "Animal rescue officers in Singapore successfully rescued a kitten that had crawled onto a the narrow ledge of a 12-story building.",
  "word:army": "Army ants have no permanent nests.",
  "word:author": "Author Salman Rushdie was stabbed in New York before a speech.",
  "word:authority": "Authority corrupts its holder and debases its victims.",
  "word:bacteria": "Bacteria can grow in a blocked pore.",
  "word:beauty": "Beauty is about feeling comfortable in your own skin.",
  "word:bill": "Bill Maher was never funny, but his politics used to be far less stodgy.",
  "word:bone": "Bone marrow transplants have become routine in the West for blood cancers, such as leukemia, and similar diseases.",
  "word:building": "Building nests and hand-feeding chicks are not long-term solutions. But the South African government's top penguin biologist, Robert Crawford, says efforts like these are necessary.",
  "word:carbon": "Carbon monoxide is colorless and odorless.",
  "word:care": "Care to embark on the journey of a lifetime with me?",
  "word:castle": "Castle observed and studied the phenomenon of self-sterility in an Ascidian, Ciona intestinalis, which is hermaphroditic.",
  "word:charity": "Charity vessels have resumed patrolling the Mediterranean to try to provide assistance to migrants in difficulty.",
  "word:chat": "Chat to your heart's content.",
  "word:city": "City officials have extended a quarantine on people exposed to SARS, including cordoning off a second hospital.",
  "word:clarity": "Clarity is more important than simplicity.",
  "word:climate": "Climate negotiators from more than 100 countries are struggling to reach a broad agreement on a new global treaty to further cut carbon emissions.",
  "word:comedy": "\"Comedy has always attacked LGBTQ people.\" \"Yes, and that's bad.\"",
  "word:computer": "Computer programming was devalued as a women's job until it became lucrative, at which point women were sidelined.",
  "word:confidence": "Confidence is the best beauty secret.",
  "word:conservation": "Conservation groups agree that, instead of being beneficial, gill plates may be harmful to human health because they contain arsenic, cadmium, and other lethal metals.",
  "word:construction": "Construction workers often wear steel-toe boots.",
  "word:contact": "Contact with radioactive waste is unlikely to give you superpowers.",
  "word:content": "Content moderation at Tatoeba is kind of a joke.",
  "word:crack": "Crack eggs, mix them with a fork, add cheese and tomatoes, then fry it all in a pan.",
  "word:crime": "\"Crime is up. We shouldn't have defunded the police.\" \"We didn't defund them. We increased their budget.\" \"Just goes to show what happens when you defund the police...\"",
  "word:crisis": "Crisis planning helps minimize the impact of unexpected events.",
  "word:data": "Data must be protected from those who misuse it.",
  "word:day": "Day and night become equal close to the date of the equinox on March 20th, marking the official start of spring.",
  "word:delivery": "Delivery drivers are more likely to die on the job than police.",
  "word:discovery": "Discovery will deliver several tons of supplies and equipment to the International Space Station, as well as a crewmember. Mission Specialist Thomas Reiter of Germany will remain on the space station for six months.",
  "word:disease": "Disease, poor water quality and decades of overharvest have drastically reduced the bay's natural oyster population.",
  "word:dish": "Dish water or bathwater should be disposed of at least 100 feet away from lakes, streams or other water sources.",
  "word:divorce": "Divorce is a human right.",
  "word:draw": "Draw a square inside the triangular figure.",
  "word:driving": "Driving alone or without a licensed adult is grounds for having your learner's permit revoked.",
  "word:drug": "Drug prohibition doesn't aim to help addicts, but to exploit their vulnerability.",
  "word:due": "Due to their huge size and luminance, they easily qualify as “first magnitude” stars.",
  "word:eating": "Eating yoghurt with your fingers is, I'm afraid, deeply ungentlemanly.",
  "word:education": "Education is the bedrock of civilization.",
  "word:elements": "Elements heavier than iron are produced during supernovae and during the merger of neutron stars.",
  "word:evidence": "Evidence of the Second Temple is actually overwhelming.",
  "word:example": "Example 4 shows how to create a filesystem that only exists for the duration of the job and is shared by all nodes.",
  "word:excuse": "Excuse me, what's the soup du jour?",
  "word:exposure": "Exposure to these chemicals can increase your risk of developing cancer.",
  "word:factory": "Factory production — the largest component of the statistic — jumped by 0.7 percent.",
  "word:farming": "Farming looks mighty easy when your plow is a pencil and you're a thousand miles from the corn field.",
  "word:fashion": "Fashion was one of the first to adapt to the new house-bound reality, making sweatpants the new American go-to attire.",
  "word:fat": "Fat actors don't need to wear fatsuits.",
  "word:ferries": "Ferries, freighters and fishing and tour boats are part of the tableau that often makes living by the sea postcard-pretty and desirable.",
  "word:finding": "Finding TB in young children, in particular, poses a hurdle because youngsters often can’t produce a sputum sample necessary to diagnose the disease.",
  "word:fish": "Fish is considered a good source of omega threes, fatty acids thought to be beneficial to health.",
  "word:flat": "Flat polished slabs of garnet are found inlaid in mosaic work in Anglo-Saxon and Merovingian jewelry, the material used being almandine, or “precious garnet.”",
  "word:formula": "Formula One teams have persuaded the sport's ruling body to allow the numbers displayed on cars next season to reflect the 2001 championship standings.",
  "word:fortune": "Fortune does not smile twice.",
  "word:freedom": "Freedom is always the freedom of dissenters.",
  "word:garbage": "Garbage despoiled the landscape where she had played as a child.",
  "word:gender": "\"Gender exploratory therapy\" is similar to \"crisis pregnancy centers,\" and advocated by the same people.",
  "word:glass": "Glass piles up waiting to be melted near the workshop, where there is also a shop selling glassware.",
  "word:gold": "Gold’s resistance to corrosion and its excellent electrical conductivity makes it very useful in the electronics industry, especially in smart phones.",
  "word:growth": "Growth forecasts for developing countries for those two years are 5.2 percent and 5.4 percent respectively.",
  "word:hand": "Hand saws have sharp teeth which helps them cut into wood.",
  "word:handling": "Handling equipment in below-zero temperatures and working with camera-shy wildlife were a serious challenge to the movie producers too. For example, an automated camera, camouflaged in white, caught a bear’s attention.",
  "word:health": "Health advocacy groups that have been warning of possible cell phone-cancer links are praising the WHO pronouncement.",
  "word:heating": "Heating boils off the liquid in the gel and the material that remains is like a hard sponge, slightly coarse and almost weightless.",
  "word:heroes": "Heroes do, in fact, do that.",
  "word:hit": "Hit me with the truth.",
  "word:horse": "Horse racing is cruel and inhumane.",
  "word:hospital": "Hospital workers tried to admit her after swabbing her for the test, but she insisted on self-quarantining herself at home.",
  "word:hunting": "Hunting for ivory on the African continent has tripled, and elephants now are facing their gravest crisis in decades, according to the U.N. Environmental Protection Agency and other conservation groups.",
  "word:identity": "Identity is a reflection of inner and outer worlds.",
  "word:information": "Information comes faster than people can process it.",
  "word:internet": "Internet trolls have twisted the concept of \"free speech\" beyond all recognition.",
  "word:king": "King Dodon, a lazy and gluttonous ruler, is greatly worried by his warlike neighbors.",
  "word:knowledge": "Knowledge rejuvenates the soul, and lightens the burden of old age.",
  "word:koala": "Koala populations are declining, largely due to habitat loss and fragmentation.",
  "word:language": "Language is often used to talk about politics.",
  "word:light": "Light from distant stars can tell scientists about the star's composition and age.",
  "word:lion": "Lion dances are a facet of traditional Chinese culture.",
  "word:lock": "Lock him up and throw away the key.",
  "word:luck": "Luck does not smile twice.",
  "word:mail": "Mail from overseas is also being X-rayed and sniffed by detector dogs as officials enter the first stage of a nationwide Emergency Animal Disease Response Plan.",
  "word:making": "Making matters worse, schools often sent the sickest children home to infect families and communities.",
  "word:male": "Male hymenopterans develop from unfertilized ova.",
  "word:mark": "Mark Zuckerberg is more of a monster than you know.",
  "word:material": "Material from space that makes it to earth can range from incredibly massive meteors to microscopic micrometeorites.",
  "word:medication": "Medication helped me a lot.",
  "word:medicine": "Medicine shouldn't be subjectively defined by cynical, power-hungry politicians.",
  "word:migration": "Migration is a basic human right.",
  "word:milk": "Milk isn't good for adult cats, and only cat milk is appropriate for kittens.",
  "word:money": "Money is so taken for granted that there is little awareness of its significance as a technology.",
  "word:muscle": "Muscle atrophy, as it's also known, is a common result of starvation and a number of very serious diseases, including cancer, diabetes and AIDS.",
  "word:museum": "Museum team member Kevin May excavates at various prehistoric sites in Alaska.",
  "word:nature": "Nature had gifted Defoe with untiring energy, a keen taste for public affairs, and a special aptitude for chicanery and intrigue.",
  "word:night": "Night was coming on and, to accent the loneliness, from somewhere in the dusky dimness a great foghorn groaned at intervals.",
  "word:north": "North Koreans are really good at drawing lines because they have a Supreme Ruler.",
  "word:note": "Note that the drawers are color-coded. Here's an explanation of what the colors mean.",
  "word:order": "Order the new Tom doll in any size, shape and color you like!",
  "word:panic": "Panic over transgender bathroom use leads to cisgender women being harassed in public.",
  "word:passages": "Passages from the Gospels were frequently used to whip up the villagers into an antisemitic frenzy, thus keeping them from ever rising up against the nobility.",
  "word:payment": "Payment must be made in advance.",
  "word:percent": "26 percent of American Jews have difficulty paying bills; this includes 55 percent of those making under $50,000 per year.",
  "word:photo": "Photo booths are found in shopping malls, beach boardwalks, amusement parks and other places.",
  "word:pink": "Pink and purple are shades of one another.",
  "word:place": "Place a few oysters at one time in a wire frying basket and immerse in smoking hot fat.",
  "word:plant": "Plant pigments such as the carotenoids and chlorophylls will react similarly when exposed to light of high intensity.",
  "word:plastic": "Plastic seems to fascinate cats.",
  "word:plate": "Plate tectonics is the area of science that explains why the Earth’s surface moves, and how those changes cause earthquakes and volcanic activity.",
  "word:police": "Police presence in the neighborhood was increased as a measure to deter crime.",
  "word:pollution": "Pollution was affecting the health of everyone in the town.",
  "word:power": "Power and religion mix too well.",
  "word:president": "President Saied wants Tunisians to vote on a new draft constitution in a July 25 referendum.",
  "word:privacy": "Privacy must be guarded at all costs.",
  "word:production": "Production came grinding to a halt.",
  "word:project": "Project 1640 is a first-of-its-kind, high-contrast imaging program which combines high-tech instrumentation and software, giving scientists the ability to spot planets orbiting distant suns in star systems outside of our solar system.",
  "word:property": "Property is theft and shoplifting is based.",
  "word:psychologist": "Psychologist Dacher Keltner says recent studies of the brain and nervous system show a biological basis for compassion and altruism.",
  "word:rain": "Rain fell all night long.",
  "word:rainfall": "Rainfall is collected for volunteer-run gardens growing ferns, palmettos and bananas.",
  "word:reader": "Reader, suppose you were an idiot. And suppose you were a member of Congress. But I repeat myself.",
  "word:reading": "Reading explanations about the same thing in different places can make it easier to understand.",
  "word:religion": "Religion consists in a set of things which the average man thinks he believes, and wishes he was certain.",
  "word:research": "Research by Duke University scientists suggests that habits leave a lasting mark on certain circuits in the brain, \"priming us to feed our cravings.\"",
  "word:retirement": "Retirement is the moment when the worker ceases his activity to rest.",
  "word:rock": "Rock is alive in the sense that jazz is still alive, and dead in the sense that jazz is dead.",
  "word:science": "Science is good at explaining the \"how,\" but not so good at explaining the \"why.\"",
  "word:sea": "Sea spiders are not arachnids, but close relatives of them.",
  "word:second": "Second City alum Tom Jackson will be co-starring.",
  "word:secretary": "Secretary General Kofi Annan says the United Nations is struggling to balance contradictory pressures as it tries to restore stability to war-torn countries.",
  "word:sex": "Sex will be a private thing when abortion is legal everywhere.",
  "word:sign": "Sign up for Common Voice newsletters, goal reminders and progress updates.",
  "word:silence": "Silence is a powerful companion.",
  "word:skin": "Skin color does not indicate ancestry or origin.",
  "word:sleep": "Sleep apnea occurs most often when sleeping in a supine position.",
  "word:sleeping": "Sleeping in your car is like camping, sort of.",
  "word:smoke": "Smoke from forest fires becomes so dense that airline flights must detour and residents across the region suffer respiratory illnesses.",
  "word:smoking": "Smoking is a nasty habit.",
  "word:sound": "Sound and signification, form and function, are inseparable in the life of language.",
  "word:south": "South Africa just need six runs to win the cricket match.",
  "word:southwest": "Southwest Airlines has promised to reimburse passengers for expenses such as hotels and car rentals in addition to refunding tickets, after it canceled thousands of flights due to a massive winter storm.",
  "word:space": "Space probes send back data from the far reaches of the solar system.",
  "word:speaking": "Speaking to American Jewish leaders at the Vatican, the pope said denial or minimization of the Shoah was intolerable and unacceptable.",
  "word:spending": "Spending time in nature is one of the best ways to improve your mood, especially if you’re living in the city, where stress is prevalent.",
  "word:stability": "Stability is a double-edged sword.",
  "word:starting": "Starting Friday, the U.N. will raise thermostats by three degrees Celsius to 25 degrees in most parts of the huge headquarters complex.",
  "word:state": "State wildlife biologist Beth Waterbury also worked on setting up a baling twine pick up and recycling program in her area.",
  "word:station": "Station wagons gave way to SUVs.",
  "word:steam": "Steam and smoke come out the chimney.",
  "word:step": "Step on the dance pad to the beat to hit the arrows scrolling up the screen.",
  "word:stock": "Stock up on canned foods.",
  "word:strength": "Strength lies in calm resolve.",
  "word:strike": "‘Strike a pose! Strike a pose!’ breathes Madonna, as her hit song ‘Vogue’ begins to ooze from an overhead speaker.",
  "word:submit": "Submit only your best work.",
  "word:sugar": "Sugar molecules in food caramelise at around 180 degree Celsius.",
  "word:tax": "Tax deductible donations and a portion of ticket revenues go into a special Carousel Restoration fund.",
  "word:teaching": "Teaching became her way of coping with the loss.",
  "word:technology": "Technology has become much more user friendly over the years.",
  "word:television": "Television and radio signals from Earth have only been traveling for about 80 years, the researchers said, adding that those transmissions have only reached about 8,531 stars and 3,555 potential Earth-like planets.",
  "word:thinking": "Thinking men and women the world over are beginning to realize that patriotism is too narrow and limited a conception to meet the necessities of our time.",
  "word:time": "Time is a great master; the trouble is that it kills its students.",
  "word:top": "Top tennis players Novak Djokovic and Andy Murray use graphene-based racquets.",
  "word:tourist": "Tourist numbers in Indonesia swelled last year on the back of overseas advertising and infrastructure development.",
  "word:trade": "Trade ministers gathered in Manila for a three-day meeting say the deal will sharply increase trade between ASEAN and Japan, which already tops 160 billion dollars.",
  "word:travel": "Travel analysts say flying business class is becoming more attractive as heightened airport security makes traveling more of a hassle.",
  "word:treatment": "Treatment for the parasitic illness schistosomiasis is more effective if children have a snack before receiving the drug praziquantel.",
  "word:type": "Type 2 diabetes impairs the body's ability to use insulin, the hormone that regulates blood sugar. The disease can damage the heart, eyes, kidneys and nerves.",
  "word:understanding": "Understanding the aquifer’s capacity to store water from year to year is important because it fills a major gap in the overall equation of meltwater runoff and sea levels.",
  "word:velvet": "Velvet fabric is often seen as a sign of luxury.",
  "word:video": "Video games are for children.",
  "word:village": "Village chiefs are trying to change that by urging people to take the jab from mobile vaccination clinics.",
  "word:volunteers": "Volunteers spend two hours each Saturday doing one-on-one lessons with the children who are first assessed to see what level they are in.",
  "word:walk": "“Walk ahead of yourself, like the dromedary who guides the caravan,” says a Tuareg proverb.",
  "word:walking": "Walking on the moon was one of humanity's greatest achievements.",
  "word:world": "World Poetry Day is March 21st.",
  "word:water": "Water may be the source of life, but its life-giving quality depends on how we treat it.",
  "word:wealth": "Wealth and success are considered synonymous, but I have found more misery in the homes of the rich than among the poor.",
  "word:west": "West and East are cardinal directions, not civilizations.",
  "word:whale": "Whale Stranding Indonesia, a nongovernmental organization, says in 2020 more than 70 marine mammals were found stranded, including dugongs, which are medium-sized marine mammals that are related to manatees.",
  "word:working": "Working from the back room of a tiny Internet cafe, 23-year-old computer whiz Zelalem Tadesse has helped Yusuf and hundreds of others to register.",
  "word:writing": "Writing a haiku is easier than writing a sonnet.",
  "word:year": "Year in and year out in this place we have naught but these little haps to lighten our thoughts.",
  "word:zero": "Zero people have ever been penalized for saying the word woman.",
  "word:additional": "Additional ice joins the main glacier from the south, avalanching down from the Jeannette Heights area.",
  "word:advanced": "Advanced language learning includes learning to talk about politics.",
  "word:amazing": "Amazing discoveries continue to be made among the famed Nazca Lines of southern Peru, and archaeologists recently revealed the never-before seen figure of a giant cat etched into a hillside in the desert.",
  "word:ancient": "Ancient Egyptians turned papyrus into paper and provided the world with it for thousands of years.",
  "word:artificial": "Artificial vermilion is also made both in China and in this country from a mixture of sulphur and mercury.",
  "word:beautiful": "Beautiful music, offered with dedication, has the power to unite people, Berkofsky says.",
  "word:biological": "Biological oceanographer Paul Snelgrove, who participated in a decade-long global census of marine life a few years ago, notes that finding new species in the deep ocean is pretty common.",
  "word:british": "British forces had begun the attack about the time the peace treaty was being signed in Ghent.",
  "word:classical": "Classical liberalism deifies abstractions and objectifies humans.",
  "word:clean": "Clean the litter box twice a day.",
  "word:common": "Common Voice is also the main source of Mozilla's virtual assistant that they're working on.",
  "word:conservative": "Conservative commentators are laughing at how stupid their listeners and readers are.",
  "word:critical": "Critical race theory emerged out of critical legal studies.",
  "word:cultural": "\"Cultural Marxism\" is an antisemitic dog whistle.",
  "word:current": "Current electoral laws stipulate that a party or coalition of parties must win 25 percent of the popular vote or 20 percent of seats in the national parliament to nominate a presidential candidate.",
  "word:dangerous": "Dangerous anarchists are conspiring to feed the homeless.",
  "word:different": "Different cultures look at history differently.",
  "word:domestic": "Domestic cats aren't too far removed from their wild ancestors.",
  "word:economic": "Economic experts warn that lockdowns could devastate the country’s economy, which is already inhibited by international sanctions.",
  "word:effective": "\"Effective altruism\" is an insane philosophy dreamt up by techbros on amphetamines.",
  "word:empty": "Empty the coffee grounds after you're done brewing.",
  "word:environmental": "Environmental observations indicate that summer burned areas in northern and central California have increased fivefold during 1996 to 2021 compared to 1971 to 1995.",
  "word:fair": "Fair Florence, the narrow Arno dividing her, the purple Appennines shutting her in the Arno’s fertile valley.",
  "word:famed": "Famed for its strong, yet delicate, aroma, Kampot pepper can range from intensely spicy to mildly sweet.",
  "word:famous": "Famous doper Lance Armstrong is claiming that trans women in sports have an unfair advantage.",
  "word:final": "Final Fantasy VI was the best Final Fantasy game.",
  "word:financial": "Financial analyst David Thwaites, of BNP Paribas in London, says unemployment will not drop from the four million mark until the middle of this year, and that is uncomfortably close to the election date.",
  "word:fine": "Fine markings around the muzzle and shoulder hint at an early bridle.",
  "word:flexible": "Flexible piping is very prominent at the rebuilt Higashinada sewage treatment plant on Kobe's waterfront.",
  "word:foreign": "Foreign Minister Nicolas Maduro says Mr. Chavez had an abscess removed from his pelvic area.",
  "word:former": "Former trainees are apprised of key changes and updates through periodic communication.",
  "word:free": "Free speech is not freedom from social consequences.",
  "word:further": "Further research is needed before a carbon nanotube biosensor for salmonella is available commercially.",
  "word:general": "General Gaïd Salah is a lion in Algeria but a worm in the West and everywhere else.",
  "word:genetic": "Genetic diversity in the Texas State Bison Herd (descended from the famous Goodnight herd, discussed here) dropped so low that in 2003, just one calf in 15 pregnancies survived to its second year.",
  "word:global": "Global cobalt prices have tripled since May 2003 and they now stand at a record $55,100 per tonne.",
  "word:heavy": "Heavy precipitation is expected in central California with rainfall totals Monday of 7 to 13 centimeters near the coast, the weather forecasters said.",
  "word:historical": "Historical materialism is a pseudoscience.",
  "word:illegal": "\"Illegal immigration\" is a fake problem made up by the right to scapegoat a vulnerable minority for the effects of neoliberal policies.",
  "word:individual": "Individual Jews do both good and bad things, just as individual non-Jews do.",
  "word:initial": "Initial tests of McIntyre's well water showed unsafe levels of toluene, a volatile and toxic petrochemical that causes nausea and headaches.",
  "word:intermediate": "Intermediate uveitis is often characterized by the sudden presence of floaters.",
  "word:international": "International rights groups including Amnesty International denounced the charges, calling them \"patently absurd\".",
  "word:isolated": "Isolated communities of Western Yiddish speakers survived into the 20th century, but the dialects are now extinct.",
  "word:key": "Key’s song gained popularity as a patriotic ditty, especially during and after the American Civil War in the 1860s.",
  "word:major": "Major U.S. stock markets made strong gains Tuesday as strong earnings reports encouraged investors.",
  "word:martial": "Martial law has been imposed in the region.",
  "word:medical": "Medical providers need to practice trauma-informed care.",
  "word:mental": "Mental healthcare isn't available to most of the working poor under neoliberalism.",
  "word:military": "Military recruiters came to our school.",
  "word:modern": "Modern art is fine. I don't understand why people hate it so intensely.",
  "word:natural": "Natural beauty is always timeless.",
  "word:northern": "Northern elephant seals are large and imposing, with significant differences in size and shape between sexes (sexual dimorphism).",
  "word:oral": "Oral cancer and cancer of the pharynx, or upper part of the throat, are especially aggressive forms of the disease that are very hard to treat.",
  "word:overall": "Overall, my visit to Bangladesh was an incredible experience.",
  "word:personal": "Personal data must be safeguarded.",
  "word:political": "Political is when you disagree with conservatives.",
  "word:pop": "\"Pop\" is one of the regional terms in the U.S. for a carbonated soft drink.",
  "word:possible": "Possible solutions to global warming range from the simple to the complex—from changing a light bulb to engineering giant reflectors in space.",
  "word:present": "Present day Benin was the site of Dahomey, a West African kingdom that rose to prominence in about 1600 and over the next two and a half centuries became a regional power.",
  "word:previous": "Previous work in tissue regeneration involved a laborious process of inserting specific genes into stem cells created from skin cells, then infusing the transformed cells into the body to create healthy tissue.",
  "word:private": "Private businesses and corrupt politicians are believed to have siphoned off billions of dollars.",
  "word:professional": "Professional and amateur musicians are more likely to keep their hearing sharper over a lifetime, according to a new study.",
  "word:psychiatric": "Psychiatric abuse is still a tremendous problem.",
  "word:public": "Public religious worship was not allowed under the atheistic communist state.",
  "word:raw": "Raw, unpasteurized sauerkraut is full of probiotics.",
  "word:regional": "Regional autonomy was a key driver of the Spanish Civil War—Franco and the nationalist army opposed the left-wing Republican government’s extension of autonomy to Catalonia and the Basques.",
  "word:regular": "Regular maintenance should keep the machine in good working order.",
  "word:rural": "Rural electrification was finally coming, even though for years nay-sayers had said it was economically infeasible.",
  "word:scientific": "Scientific analyses disproved the rumors, but the damage was done.",
  "word:several": "Several thousand fans showed up to watch the USA-Germany game on big screens in a Washington neighborhood.",
  "word:silver": "Silver nitrate solution added to an aqueous solution of salvarsan acidified with dilute nitric acid yields a dark-yellow precipitate which rapidly becomes black.",
  "word:similar": "Similar bad-faith arguments are made against the words \"goy\" and \"cis.\"",
  "word:simple": "Simple bandages are usually seen as the first line of attack in healing small to moderate wounds and burns.",
  "word:social": "Social media leads to the amplification of once-fringe views, for better or worse.",
  "word:solar": "Solar flares are bursts of energy from the sun that can affect satellites and communication on Earth.",
  "word:special": "Special cases aren't special enough to break the rules.",
  "word:specialized": "Specialized instruments are used to uncover any hidden pockets of water.",
  "word:strong": "Strong acid stain removers destroy cotton and linen cloth; even mild acids, such as lemon juice and vinegar, may injure cotton and linen if allowed to remain too long on the cloth.",
  "word:successful": "Successful fascists today are savvy enough not to call themselves fascists.",
  "word:traditional": "Traditional fogging mists miss many of the hidden insects, and it can take several expensive visits, plus wholesale laundering of all your linens and clothing, to get rid of them.",
  "word:underground": "Underground or aboveground travel would be immune to weather changes and collisions and would require little energy.",
  "word:united": "United Nations food agencies are warning that COVID-19, conflict and lack of humanitarian aid are increasing levels of acute hunger around the world, with several countries and one region on the brink of famine.",
  "word:virtual": "Virtual visitors can also view hundreds of photos and videos on the museum’s Facebook page, and there’s storytime for kids, and art classes for people of all ages.",
  "word:western": "Western New York isn't much different from the rest of the Rust Belt.",
  "word:wise": "Wise men told him his simple fancies were inane and childish, and he believed it because he could see that they might easily be so.",
  "word:almost": "Almost all life on Earth depends on food produced by organisms that photosynthesize.",
  "word:currently": "Currently, most of that data is expensive and proprietary.",
  "word:directly": "Directly opposite his Majesty were eight of his sons, richly dressed in velvet and gold-brocade coats, all glittering with gold and jewels.",
  "word:originally": "Originally designed by Japanese researchers for influenza, the drug is a nucleoside analogue — a molecule that looks like a building block of genetic material.",
  "word:professionally": "Professionally, I wouldn't apply to a job to translate into a language other than my native one.",
  "word:appearances": "Appearances may be different when using other skins.",
  "word:bones": "Bones that have been languishing in obscurity for nearly 80 years at a London museum may actually belong to the oldest known dinosaur.",
  "word:decades": "Decades of research have demonstrated that beating children is both ineffective and extremely psychologically damaging.",
  "word:drugs": "Drugs are too expensive to waste by putting them in Halloween candy for children.",
  "word:engineers": "Engineers in New Orleans said they expected heavy rains to cause some flooding, but the storm had not breached levee walls built to hold back Lake Pontchartrain.",
  "word:investigators": "Investigators suspect the outbreak was caused by a batch of contaminated steroid injections given to more than 13000 people across the country to relieve chronic back or joint pain.",
  "word:knives": "Knives stung me and blackjacks smashed against me, but I laughed and drove my iron fists in straight, steam-hammer smashes that shattered flesh and bone.",
  "word:lawyers": "Lawyers by day, two Ugandan women are raving about their enthusiasm and love for natural hair, encouraging other women to stop straightening their hair or using hair extensions and keep it natural.",
  "word:philosophers": "Philosophers distinguish between a priori and a posteriori knowledge.",
  "word:plus": "Plus, Kenya ramps up efforts to control the twin challenges of COVID-19 and malaria.",
  "word:profits": "Profits are the unpaid wages of the working class.",
  "word:readers": "Readers see a teenager rollerblading in the streets of Dakar, a DJ playing music in Lagos, a couple looking at the Atlantic Ocean in Cape Town.",
  "word:regulations": "Regulations are written in blood.",
  "word:robots": "Robots have taken over many mundane tasks in our world, from heavy industry to sorting merchandise to bomb disposal.",
  "word:scores": "Scores of villagers watch and shout as over a hundred elephants trample millet farms in the suburbs of Cameroon’s northern town of Kaele.",
  "word:spiders": "Spiders, a unique class of creatures known as arachnids, come in 43,000 varieties and have thrived for nearly 300 million years on every continent except Antarctica.",
  "word:stars": "Stars can live for millions to billions of years before they burn out.",
  "word:access": "Access to the internet has been intermittent in the past week, with certain apps and websites blocked, including Facebook, where citizens had been posting livestreams of protests.",
  "word:according": "According to Judaism, Elijah will return to herald the coming of the Messiah.",
  "word:breeding": "Breeding leaves dogs and cats with a number of medical conditions.",
  "word:depression": "Depression does that to you.",
  "word:business": "Business mogul Sam Matekane's upstart political party, the Revolution for Prosperity, won 56 of the 120 constituencies in general elections but fell short of his goal of winning an outright 61-seat majority.",
  "word:better": "Better to be alone than in a bad company.",
  "word:blood": "Blood from umbilical cords has been used in life-saving transplants for people suffering from diseases such as leukemia.",
  "word:connect": "Connect Sirius, the Gemini twins, Capella, Aldebaran, Rigel, and then back to Sirius, and you have completed the Great Hexagon!",
  "word:cattle": "Cattle ranchers also discovered their animals could eat the tree's leaves and fruits.",
  "word:commercial": "Commercial fishing began in the lake in the 1950's, and now hauls in over 200,000 tons of fish a year.",
  "word:communication": "Communication is the path to peace.",
  "word:community": "Community leaders say current efforts have been unsuccessful and oil continues to gush from the damaged well.",
  "word:coffee": "Coffee roasters combine beans from different areas to make coffees with different tastes and qualities.",
  "word:running": "Running through the fields, I felt alive.",
  "word:discuss": "Discuss your decision to pursue medicine. When did you decide to become an MD, and why?",
  "word:poor": "Poor safety practices are common among people who prioritize profit above all else.",
  "word:congress": "Congress and committees of Congress of course impeded the executive when there was no coercive public sentiment to check and rule them.",
  "word:food": "Food companies are jacking up prices under the cover of \"inflation\" and making record profits.",
  "word:matter": "Matter cannot be created or destroyed, but only transformed.",
  "word:mass": "Mass shootings require a high amount of executive function to plan and execute.",
  "word:million": "1.5 million Armenians died in the Armenian genocide.",
  "word:professor": "Professor Jackson drew a deterministic finite automaton on the board.",
  "word:russia": "Russia colonizing Ukraine has no impact on its ability to become a superpower again.",
  "word:scottish": "Scottish First Minister Nicola Sturgeon, proponent of an independence referendum, responded Tuesday to Johnson’s comments via Twitter.",
  "word:shuttle": "Shuttle officials say lightweight insulating foam that flew off Columbia's external fuel tank broke into dust and was not heavy enough to have damaged its left wing.",
  "word:success": "Success is accomplishing what you set out to do.",
  "word:concession": "Concession stand food is usually overpriced.",
  "word:traffic": "Traffic gridlock, soaring property prices and the influx of migrant workers are putting pressure on the country's laidback lifestyle.",
  "word:weed": "Weed is legal in New York.",
  "word:website": "Website administrators who ask for discussions of their decisions to take place in private are trying to avoid accountability.",
  "word:studio": "Studio estimates on November 11 had Jerry Seinfeld's animated comedy totalling $72.2 million in total receipts.",
  "word:poverty": "Poverty is something we, as a society, choose to have.",
  "word:rape": "Rape is not part of a prison sentence; people aren't sentenced to rape.",
  "word:congratulations": "Congratulations on the publication. My French isn't good enough to read poetry yet.",
  "word:amateur": "Amateur naturalists begin their bee hunts by noting the time of day and location they are photographing.",
  "word:trails": "Trails leading to the top and bottom of the falls are popular among sunbathers, swimmers, and fishermen, so plan on having company unless you arrive earlier.",
  "word:miniature": "Miniature Aerial Vehicles are commonly used today for a variety of tasks, but they are mostly guided by humans using Global Positioning System technology.",
  "word:shellfish": "Shellfish are just giant bugs.",
  "word:parliament": "Parliament approved a major government reshuffle Saturday involving 13 ministerial changes.",
  "word:medieval": "Medieval England buried people alive for merely associating with Jews.",
  "word:tropical": "Tropical Storm Isaias is expected to strengthen into a low-level hurricane before it makes landfall along the coast of the Carolinas.",
  "word:tourists": "Tourists can go on a guided tour inside the windmill.",
  "word:journalists": "Journalists must be careful that seeking balance doesn’t lead to unfair reporting, or setting up an unfair moral equivalency or balance, between unequal sides in an argument.",
  "word:evolutionary": "Evolutionary psychology generally does not make testable predictions, so it is often viewed as a pseudoscience.",
  "word:cognitive": "Cognitive behavioral therapy doesn't work for everything or everyone.",
  "word:commitment": "Commitment is like kryptonite to Tom.",
  "word:hormone": "Hormone replacement therapy for transgender people is lifesaving.",
  "word:justice": "Justice is a scam by Big Government to sell more government.",
  "word:manufacturers": "Manufacturers are trying to dazzle prospective buyers with electric propulsion, better performance, comfort, style and better mileage.",
  "word:nuts": "Nuts may be purchased shelled or unshelled with the exception of cashews, which are sold only shelled.",
  "word:intelligence": "Intelligence services in Algeria instead of spying on dangerous people they spy on modernist opponents and the oppressed.",
  "word:gravity": "Gravity is what keeps planets in orbit around stars.",
  "word:drought": "Drought is not the only enemy. Striga is a parasitic weed that Africans commonly call witchweed. The plant attacks sorghum and other crops and steals water and nutrients from the roots.",
  "word:cosmetics": "Cosmetics company heir and art collector Leonard Lauder is donating his $1 billion Cubist art collection to New York City's famed Metropolitan Museum of Art.",
  "word:butterflies": "Butterflies are fluttering all over the place.",
  "word:amber": "Amber Heard was deprived of her right to a fair trial in Virginia.",
  "word:predators": "Predators like baboon and hyena are deterred by the lake's high salinity.",
  "word:cement": "Cement is the glue holding concrete together, and it is the manufacture of cement that creates concrete's substantial carbon footprint.",
  "word:lizard": "Lizard people probably aren't real.",
  "word:sustainable": "Sustainable fishing methods may help save Gobies, one of the largest families of marine fish.",
  "word:journalism": "Journalism should at least be a little biased.",
  "word:remember": "Remember to eat lots of bran to keep your bowels moving.",
  "word:evolution": "Evolution is a tinkerer and not an engineer.",
  "word:critics": "Critics were right to point out that the politician led a nascent fascist movement.",
  "word:lions": "Lions greet members of their pride by bunting.",
  "word:chemist": "Chemist Charles Cantrell analyzed properties of the smoke and identified a number of active compounds that repel insects, including — for the first time, he says — triglycerides, a type of fat.",
  "word:numerous": "Numerous negative health effects of smoking have been researched and described over the years, beginning with the U.S. surgeon general’s report in 1964.",
  "word:livestock": "Livestock overgrazing can lead to outbreaks of ravenous locusts, according to a new study.",
  "word:rumor": "Rumor has it that Martin Scorsese is working on a gangster movie.",
  "word:jealousy": "Jealousy is a personal problem.",
  "word:capitalism": "Capitalism gives an insane amount of power to people who did not earn it.",
  "word:resilience": "Resilience is built one challenge at a time.",
  "word:wool": "Wool and mohair are the bread and butter of many of the Basotho, the people of Lesotho.",
  "word:prayer": "Prayer in schools is more likely to lead to child grooming than teaching about LGBTQ people.",
  "word:prison": "Prison guards found a shiv in Tom's cell.",
  "word:patients": "Patients with hypertension should be monitored closely when taking this medication.",
  "word:politics": "Politics is the abuse of the masses.",
  "word:set": "Set and setting are important when doing psychedelics.",
  "word:approximately": "Approximately one-half of 1% of the planet’s water is drinkable, and we use that water for much more than drinking—showering, brushing our teeth, watering our grass, etc.",
  "word:democratic": "Democratic presidential candidate Hillary Clinton says \"steadiness\" is the most important characteristic a president must have.",
  "word:cricket": "Cricket is the most popular sport in Bangladesh.",
  "word:indigenous": "Indigenous Americans discovered America more than 10,000 years ago.",
  "word:imaginative": "Imaginative craftsman as he was, Morris was never quite an artist in the strict sense of the word.",
  "word:vulnerable": "Vulnerable indigenous species, including the flightless Tasmanian native hen and bettongs, which are small nocturnal marsupials, would be at particular risk.",
  "word:ivory": "Ivory Coast’s National Order of Architects has opened the country’s first professional architecture school, where professors want to instill in students an understanding of the country’s specific building needs and heritage.",
  "word:tusk": "Tusk is not my favorite Fleetwood Mac album.",
  "word:recovery": "Recovery from a mental health condition isn't just about therapy and medication, but about your goals for the future.",
  "word:chef": "Chef Majed cracks eggs into a mixer and blends mayonnaise when we meet in Washington.",
  "word:fog": "Fog can form quickly and catch boaters off guard. Visibility can be reduced to a few feet, which can disorient even the most experienced boaters.",
  "word:ambassador": "Ambassador Mark Lippert told reporters Tuesday he feels \"pretty darn good, all things considered\" and expects to make a full recovery.",
  "word:string": "String theory has been wildly overhyped by its researchers.",
  "word:cv": "CV stands for curriculum vitae.",
  "word:genius": "Genius is insanity that's useful.",
  "word:intricate": "Intricate design, white flowers and see-through veils. A happy bride proudly wears her perfect wedding attire, this time, however, made from toilet paper!",
  "word:mango": "Mango ice cream is a popular summer treat.",
  "word:strawberry": "Strawberry shortcake is easy to make vegan.",
  "word:technique": "Technique is technique, no matter who teaches it.",
  "word:radiation": "Radiation and convection carry that energy outward to the star's surface and to its atmosphere beyond.",
  "word:conventional": "Conventional wisdom is that this will work; however, it won't.",
  "word:chemistry": "Chemistry is the study of stuff and what it does.",
  "word:history": "History, Stephen said, is a nightmare from which I am trying to awake.",
  "word:mathematics": "Mathematics is just a subset of type theory.",
  "word:mining": "Mining is bound to become a still stronger factor in civilization as metallurgical processes multiply and there are discovered means of more economically extracting the valuable contents of ores.",
  "phrase:a couple of": "A couple of years ago, Seraphic Fire received a $25,000 grant and decided to tackle a big project: recording Claudio Monteverdi's Vespers of 1610, one of the greatest choral works of all time.",
  "phrase:at least": "At least now you know not to approach stray dogs with food in your hand.",
  "phrase:carbon dioxide": "Carbon dioxide, methane and nitrous oxide, the main man-made greenhouse gases blamed for global warming, increased to record post-industrial concentrations last year, according to a report by the World Meteorological Organization.",
  "phrase:check in": "Check in between the cushions.",
  "phrase:life expectancy": "Life expectancy in Africa rose by nearly 10 years between 2000 and 2019, from 46 years to 56 years, according to the World Health Organization's State of Health in Africa report released Thursday.",
  "phrase:millions of": "Millions of Americans feed wild birds in their backyards, from cardinals and English sparrows to blue jays and doves.",
  "phrase:plastic bags": "Plastic bags blemish rural and urban scenery, damage ground water and soils, and choke livestock and fish, entangle birds and threaten animals in general.",
  "phrase:previous studies": "Previous studies have identified family history and abnormal growths, called colon polyps, as the main factors for colorectal cancer.",
  "phrase:public health": "Public health experts say they fear the variant could overwhelm Zimbabwe's collapsed health care system.",
  "phrase:safety regulations": "Safety regulations are written in blood.",
  "phrase:science fiction": "Science and science fiction intersected recently when 1,000 people took part in a brain experiment while watching a movie about what happens when the human brain is connected to a computer.",
  "phrase:scientific research": "Scientific research changes the world.",
  "phrase:space shuttle": "Space station ground controllers will test their ability to command a small flatcar to roll along tracks on a 13-meter girder that space shuttle Atlantis astronauts mounted on the station last week.",
  "phrase:the old": "The old don't want to let go of power.",
  "phrase:the poor": "The wealthy display their dazzling luxury, the poor drape themselves proudly in their rags.",
  "phrase:the milky way": "The solar system is just a tiny part of the Milky Way galaxy.",
  "phrase:under pressure": "Under pressure, those aneurysms can expand like balloons, stretching the arterial wall.",
  "phrase:wild animals": "Wild animals belong in the wild.",
  "phrase:yellow fever": "Yellow fever is a viral disease affecting the liver and kidneys, causing high fever and a yellowing of the skin and eyes.",
  "phrase:disabled people": "Disabled people are disabled by a world that does not accommodate us, rather than by our unique bodies or brains.",
  "phrase:local residents": "Local residents believe the condemned buildings attract crime.",
  "phrase:crisis management": "Crisis management is about staying calm under pressure.",
  "phrase:quality of life": "Quality of life is what's most important.",
};
